/* Autogenerated by generate_csr.sh */
#include "csrregs.h"

/* ustatus */

TEXT csr_read_ustatus(SB), $-4
	CSRRS CSR(CSR_ustatus), R0, R8
	RET

TEXT csr_write_ustatus(SB), $-4
	CSRRW CSR(CSR_ustatus), R8, R8
	RET

TEXT csr_set_ustatus(SB), $-4
	CSRRS CSR(CSR_ustatus), R8, R8
	RET

TEXT csr_clear_ustatus(SB), $-4
	CSRRC CSR(CSR_ustatus), R8, R8
	RET

/* uie */

TEXT csr_read_uie(SB), $-4
	CSRRS CSR(CSR_uie), R0, R8
	RET

TEXT csr_write_uie(SB), $-4
	CSRRW CSR(CSR_uie), R8, R8
	RET

TEXT csr_set_uie(SB), $-4
	CSRRS CSR(CSR_uie), R8, R8
	RET

TEXT csr_clear_uie(SB), $-4
	CSRRC CSR(CSR_uie), R8, R8
	RET

/* utvec */

TEXT csr_read_utvec(SB), $-4
	CSRRS CSR(CSR_utvec), R0, R8
	RET

TEXT csr_write_utvec(SB), $-4
	CSRRW CSR(CSR_utvec), R8, R8
	RET

TEXT csr_set_utvec(SB), $-4
	CSRRS CSR(CSR_utvec), R8, R8
	RET

TEXT csr_clear_utvec(SB), $-4
	CSRRC CSR(CSR_utvec), R8, R8
	RET

/* uscratch */

TEXT csr_read_uscratch(SB), $-4
	CSRRS CSR(CSR_uscratch), R0, R8
	RET

TEXT csr_write_uscratch(SB), $-4
	CSRRW CSR(CSR_uscratch), R8, R8
	RET

TEXT csr_set_uscratch(SB), $-4
	CSRRS CSR(CSR_uscratch), R8, R8
	RET

TEXT csr_clear_uscratch(SB), $-4
	CSRRC CSR(CSR_uscratch), R8, R8
	RET

/* uepc */

TEXT csr_read_uepc(SB), $-4
	CSRRS CSR(CSR_uepc), R0, R8
	RET

TEXT csr_write_uepc(SB), $-4
	CSRRW CSR(CSR_uepc), R8, R8
	RET

TEXT csr_set_uepc(SB), $-4
	CSRRS CSR(CSR_uepc), R8, R8
	RET

TEXT csr_clear_uepc(SB), $-4
	CSRRC CSR(CSR_uepc), R8, R8
	RET

/* ucause */

TEXT csr_read_ucause(SB), $-4
	CSRRS CSR(CSR_ucause), R0, R8
	RET

TEXT csr_write_ucause(SB), $-4
	CSRRW CSR(CSR_ucause), R8, R8
	RET

TEXT csr_set_ucause(SB), $-4
	CSRRS CSR(CSR_ucause), R8, R8
	RET

TEXT csr_clear_ucause(SB), $-4
	CSRRC CSR(CSR_ucause), R8, R8
	RET

/* utval */

TEXT csr_read_utval(SB), $-4
	CSRRS CSR(CSR_utval), R0, R8
	RET

TEXT csr_write_utval(SB), $-4
	CSRRW CSR(CSR_utval), R8, R8
	RET

TEXT csr_set_utval(SB), $-4
	CSRRS CSR(CSR_utval), R8, R8
	RET

TEXT csr_clear_utval(SB), $-4
	CSRRC CSR(CSR_utval), R8, R8
	RET

/* uip */

TEXT csr_read_uip(SB), $-4
	CSRRS CSR(CSR_uip), R0, R8
	RET

TEXT csr_write_uip(SB), $-4
	CSRRW CSR(CSR_uip), R8, R8
	RET

TEXT csr_set_uip(SB), $-4
	CSRRS CSR(CSR_uip), R8, R8
	RET

TEXT csr_clear_uip(SB), $-4
	CSRRC CSR(CSR_uip), R8, R8
	RET

/* fflags */

TEXT csr_read_fflags(SB), $-4
	CSRRS CSR(CSR_fflags), R0, R8
	RET

TEXT csr_write_fflags(SB), $-4
	CSRRW CSR(CSR_fflags), R8, R8
	RET

TEXT csr_set_fflags(SB), $-4
	CSRRS CSR(CSR_fflags), R8, R8
	RET

TEXT csr_clear_fflags(SB), $-4
	CSRRC CSR(CSR_fflags), R8, R8
	RET

/* frm */

TEXT csr_read_frm(SB), $-4
	CSRRS CSR(CSR_frm), R0, R8
	RET

TEXT csr_write_frm(SB), $-4
	CSRRW CSR(CSR_frm), R8, R8
	RET

TEXT csr_set_frm(SB), $-4
	CSRRS CSR(CSR_frm), R8, R8
	RET

TEXT csr_clear_frm(SB), $-4
	CSRRC CSR(CSR_frm), R8, R8
	RET

/* fcsr */

TEXT csr_read_fcsr(SB), $-4
	CSRRS CSR(CSR_fcsr), R0, R8
	RET

TEXT csr_write_fcsr(SB), $-4
	CSRRW CSR(CSR_fcsr), R8, R8
	RET

TEXT csr_set_fcsr(SB), $-4
	CSRRS CSR(CSR_fcsr), R8, R8
	RET

TEXT csr_clear_fcsr(SB), $-4
	CSRRC CSR(CSR_fcsr), R8, R8
	RET

/* cycle */

TEXT csr_read_cycle(SB), $-4
	CSRRS CSR(CSR_cycle), R0, R8
	RET

TEXT csr_write_cycle(SB), $-4
	CSRRW CSR(CSR_cycle), R8, R8
	RET

TEXT csr_set_cycle(SB), $-4
	CSRRS CSR(CSR_cycle), R8, R8
	RET

TEXT csr_clear_cycle(SB), $-4
	CSRRC CSR(CSR_cycle), R8, R8
	RET

/* time */

TEXT csr_read_time(SB), $-4
	CSRRS CSR(CSR_time), R0, R8
	RET

TEXT csr_write_time(SB), $-4
	CSRRW CSR(CSR_time), R8, R8
	RET

TEXT csr_set_time(SB), $-4
	CSRRS CSR(CSR_time), R8, R8
	RET

TEXT csr_clear_time(SB), $-4
	CSRRC CSR(CSR_time), R8, R8
	RET

/* instret */

TEXT csr_read_instret(SB), $-4
	CSRRS CSR(CSR_instret), R0, R8
	RET

TEXT csr_write_instret(SB), $-4
	CSRRW CSR(CSR_instret), R8, R8
	RET

TEXT csr_set_instret(SB), $-4
	CSRRS CSR(CSR_instret), R8, R8
	RET

TEXT csr_clear_instret(SB), $-4
	CSRRC CSR(CSR_instret), R8, R8
	RET

/* hpmcounter3 */

TEXT csr_read_hpmcounter3(SB), $-4
	CSRRS CSR(CSR_hpmcounter3), R0, R8
	RET

TEXT csr_write_hpmcounter3(SB), $-4
	CSRRW CSR(CSR_hpmcounter3), R8, R8
	RET

TEXT csr_set_hpmcounter3(SB), $-4
	CSRRS CSR(CSR_hpmcounter3), R8, R8
	RET

TEXT csr_clear_hpmcounter3(SB), $-4
	CSRRC CSR(CSR_hpmcounter3), R8, R8
	RET

/* hpmcounter4 */

TEXT csr_read_hpmcounter4(SB), $-4
	CSRRS CSR(CSR_hpmcounter4), R0, R8
	RET

TEXT csr_write_hpmcounter4(SB), $-4
	CSRRW CSR(CSR_hpmcounter4), R8, R8
	RET

TEXT csr_set_hpmcounter4(SB), $-4
	CSRRS CSR(CSR_hpmcounter4), R8, R8
	RET

TEXT csr_clear_hpmcounter4(SB), $-4
	CSRRC CSR(CSR_hpmcounter4), R8, R8
	RET

/* hpmcounter5 */

TEXT csr_read_hpmcounter5(SB), $-4
	CSRRS CSR(CSR_hpmcounter5), R0, R8
	RET

TEXT csr_write_hpmcounter5(SB), $-4
	CSRRW CSR(CSR_hpmcounter5), R8, R8
	RET

TEXT csr_set_hpmcounter5(SB), $-4
	CSRRS CSR(CSR_hpmcounter5), R8, R8
	RET

TEXT csr_clear_hpmcounter5(SB), $-4
	CSRRC CSR(CSR_hpmcounter5), R8, R8
	RET

/* hpmcounter6 */

TEXT csr_read_hpmcounter6(SB), $-4
	CSRRS CSR(CSR_hpmcounter6), R0, R8
	RET

TEXT csr_write_hpmcounter6(SB), $-4
	CSRRW CSR(CSR_hpmcounter6), R8, R8
	RET

TEXT csr_set_hpmcounter6(SB), $-4
	CSRRS CSR(CSR_hpmcounter6), R8, R8
	RET

TEXT csr_clear_hpmcounter6(SB), $-4
	CSRRC CSR(CSR_hpmcounter6), R8, R8
	RET

/* hpmcounter7 */

TEXT csr_read_hpmcounter7(SB), $-4
	CSRRS CSR(CSR_hpmcounter7), R0, R8
	RET

TEXT csr_write_hpmcounter7(SB), $-4
	CSRRW CSR(CSR_hpmcounter7), R8, R8
	RET

TEXT csr_set_hpmcounter7(SB), $-4
	CSRRS CSR(CSR_hpmcounter7), R8, R8
	RET

TEXT csr_clear_hpmcounter7(SB), $-4
	CSRRC CSR(CSR_hpmcounter7), R8, R8
	RET

/* hpmcounter8 */

TEXT csr_read_hpmcounter8(SB), $-4
	CSRRS CSR(CSR_hpmcounter8), R0, R8
	RET

TEXT csr_write_hpmcounter8(SB), $-4
	CSRRW CSR(CSR_hpmcounter8), R8, R8
	RET

TEXT csr_set_hpmcounter8(SB), $-4
	CSRRS CSR(CSR_hpmcounter8), R8, R8
	RET

TEXT csr_clear_hpmcounter8(SB), $-4
	CSRRC CSR(CSR_hpmcounter8), R8, R8
	RET

/* hpmcounter9 */

TEXT csr_read_hpmcounter9(SB), $-4
	CSRRS CSR(CSR_hpmcounter9), R0, R8
	RET

TEXT csr_write_hpmcounter9(SB), $-4
	CSRRW CSR(CSR_hpmcounter9), R8, R8
	RET

TEXT csr_set_hpmcounter9(SB), $-4
	CSRRS CSR(CSR_hpmcounter9), R8, R8
	RET

TEXT csr_clear_hpmcounter9(SB), $-4
	CSRRC CSR(CSR_hpmcounter9), R8, R8
	RET

/* hpmcounter10 */

TEXT csr_read_hpmcounter10(SB), $-4
	CSRRS CSR(CSR_hpmcounter10), R0, R8
	RET

TEXT csr_write_hpmcounter10(SB), $-4
	CSRRW CSR(CSR_hpmcounter10), R8, R8
	RET

TEXT csr_set_hpmcounter10(SB), $-4
	CSRRS CSR(CSR_hpmcounter10), R8, R8
	RET

TEXT csr_clear_hpmcounter10(SB), $-4
	CSRRC CSR(CSR_hpmcounter10), R8, R8
	RET

/* hpmcounter11 */

TEXT csr_read_hpmcounter11(SB), $-4
	CSRRS CSR(CSR_hpmcounter11), R0, R8
	RET

TEXT csr_write_hpmcounter11(SB), $-4
	CSRRW CSR(CSR_hpmcounter11), R8, R8
	RET

TEXT csr_set_hpmcounter11(SB), $-4
	CSRRS CSR(CSR_hpmcounter11), R8, R8
	RET

TEXT csr_clear_hpmcounter11(SB), $-4
	CSRRC CSR(CSR_hpmcounter11), R8, R8
	RET

/* hpmcounter12 */

TEXT csr_read_hpmcounter12(SB), $-4
	CSRRS CSR(CSR_hpmcounter12), R0, R8
	RET

TEXT csr_write_hpmcounter12(SB), $-4
	CSRRW CSR(CSR_hpmcounter12), R8, R8
	RET

TEXT csr_set_hpmcounter12(SB), $-4
	CSRRS CSR(CSR_hpmcounter12), R8, R8
	RET

TEXT csr_clear_hpmcounter12(SB), $-4
	CSRRC CSR(CSR_hpmcounter12), R8, R8
	RET

/* hpmcounter13 */

TEXT csr_read_hpmcounter13(SB), $-4
	CSRRS CSR(CSR_hpmcounter13), R0, R8
	RET

TEXT csr_write_hpmcounter13(SB), $-4
	CSRRW CSR(CSR_hpmcounter13), R8, R8
	RET

TEXT csr_set_hpmcounter13(SB), $-4
	CSRRS CSR(CSR_hpmcounter13), R8, R8
	RET

TEXT csr_clear_hpmcounter13(SB), $-4
	CSRRC CSR(CSR_hpmcounter13), R8, R8
	RET

/* hpmcounter14 */

TEXT csr_read_hpmcounter14(SB), $-4
	CSRRS CSR(CSR_hpmcounter14), R0, R8
	RET

TEXT csr_write_hpmcounter14(SB), $-4
	CSRRW CSR(CSR_hpmcounter14), R8, R8
	RET

TEXT csr_set_hpmcounter14(SB), $-4
	CSRRS CSR(CSR_hpmcounter14), R8, R8
	RET

TEXT csr_clear_hpmcounter14(SB), $-4
	CSRRC CSR(CSR_hpmcounter14), R8, R8
	RET

/* hpmcounter15 */

TEXT csr_read_hpmcounter15(SB), $-4
	CSRRS CSR(CSR_hpmcounter15), R0, R8
	RET

TEXT csr_write_hpmcounter15(SB), $-4
	CSRRW CSR(CSR_hpmcounter15), R8, R8
	RET

TEXT csr_set_hpmcounter15(SB), $-4
	CSRRS CSR(CSR_hpmcounter15), R8, R8
	RET

TEXT csr_clear_hpmcounter15(SB), $-4
	CSRRC CSR(CSR_hpmcounter15), R8, R8
	RET

/* hpmcounter16 */

TEXT csr_read_hpmcounter16(SB), $-4
	CSRRS CSR(CSR_hpmcounter16), R0, R8
	RET

TEXT csr_write_hpmcounter16(SB), $-4
	CSRRW CSR(CSR_hpmcounter16), R8, R8
	RET

TEXT csr_set_hpmcounter16(SB), $-4
	CSRRS CSR(CSR_hpmcounter16), R8, R8
	RET

TEXT csr_clear_hpmcounter16(SB), $-4
	CSRRC CSR(CSR_hpmcounter16), R8, R8
	RET

/* hpmcounter17 */

TEXT csr_read_hpmcounter17(SB), $-4
	CSRRS CSR(CSR_hpmcounter17), R0, R8
	RET

TEXT csr_write_hpmcounter17(SB), $-4
	CSRRW CSR(CSR_hpmcounter17), R8, R8
	RET

TEXT csr_set_hpmcounter17(SB), $-4
	CSRRS CSR(CSR_hpmcounter17), R8, R8
	RET

TEXT csr_clear_hpmcounter17(SB), $-4
	CSRRC CSR(CSR_hpmcounter17), R8, R8
	RET

/* hpmcounter18 */

TEXT csr_read_hpmcounter18(SB), $-4
	CSRRS CSR(CSR_hpmcounter18), R0, R8
	RET

TEXT csr_write_hpmcounter18(SB), $-4
	CSRRW CSR(CSR_hpmcounter18), R8, R8
	RET

TEXT csr_set_hpmcounter18(SB), $-4
	CSRRS CSR(CSR_hpmcounter18), R8, R8
	RET

TEXT csr_clear_hpmcounter18(SB), $-4
	CSRRC CSR(CSR_hpmcounter18), R8, R8
	RET

/* hpmcounter19 */

TEXT csr_read_hpmcounter19(SB), $-4
	CSRRS CSR(CSR_hpmcounter19), R0, R8
	RET

TEXT csr_write_hpmcounter19(SB), $-4
	CSRRW CSR(CSR_hpmcounter19), R8, R8
	RET

TEXT csr_set_hpmcounter19(SB), $-4
	CSRRS CSR(CSR_hpmcounter19), R8, R8
	RET

TEXT csr_clear_hpmcounter19(SB), $-4
	CSRRC CSR(CSR_hpmcounter19), R8, R8
	RET

/* hpmcounter20 */

TEXT csr_read_hpmcounter20(SB), $-4
	CSRRS CSR(CSR_hpmcounter20), R0, R8
	RET

TEXT csr_write_hpmcounter20(SB), $-4
	CSRRW CSR(CSR_hpmcounter20), R8, R8
	RET

TEXT csr_set_hpmcounter20(SB), $-4
	CSRRS CSR(CSR_hpmcounter20), R8, R8
	RET

TEXT csr_clear_hpmcounter20(SB), $-4
	CSRRC CSR(CSR_hpmcounter20), R8, R8
	RET

/* hpmcounter21 */

TEXT csr_read_hpmcounter21(SB), $-4
	CSRRS CSR(CSR_hpmcounter21), R0, R8
	RET

TEXT csr_write_hpmcounter21(SB), $-4
	CSRRW CSR(CSR_hpmcounter21), R8, R8
	RET

TEXT csr_set_hpmcounter21(SB), $-4
	CSRRS CSR(CSR_hpmcounter21), R8, R8
	RET

TEXT csr_clear_hpmcounter21(SB), $-4
	CSRRC CSR(CSR_hpmcounter21), R8, R8
	RET

/* hpmcounter22 */

TEXT csr_read_hpmcounter22(SB), $-4
	CSRRS CSR(CSR_hpmcounter22), R0, R8
	RET

TEXT csr_write_hpmcounter22(SB), $-4
	CSRRW CSR(CSR_hpmcounter22), R8, R8
	RET

TEXT csr_set_hpmcounter22(SB), $-4
	CSRRS CSR(CSR_hpmcounter22), R8, R8
	RET

TEXT csr_clear_hpmcounter22(SB), $-4
	CSRRC CSR(CSR_hpmcounter22), R8, R8
	RET

/* hpmcounter23 */

TEXT csr_read_hpmcounter23(SB), $-4
	CSRRS CSR(CSR_hpmcounter23), R0, R8
	RET

TEXT csr_write_hpmcounter23(SB), $-4
	CSRRW CSR(CSR_hpmcounter23), R8, R8
	RET

TEXT csr_set_hpmcounter23(SB), $-4
	CSRRS CSR(CSR_hpmcounter23), R8, R8
	RET

TEXT csr_clear_hpmcounter23(SB), $-4
	CSRRC CSR(CSR_hpmcounter23), R8, R8
	RET

/* hpmcounter24 */

TEXT csr_read_hpmcounter24(SB), $-4
	CSRRS CSR(CSR_hpmcounter24), R0, R8
	RET

TEXT csr_write_hpmcounter24(SB), $-4
	CSRRW CSR(CSR_hpmcounter24), R8, R8
	RET

TEXT csr_set_hpmcounter24(SB), $-4
	CSRRS CSR(CSR_hpmcounter24), R8, R8
	RET

TEXT csr_clear_hpmcounter24(SB), $-4
	CSRRC CSR(CSR_hpmcounter24), R8, R8
	RET

/* hpmcounter25 */

TEXT csr_read_hpmcounter25(SB), $-4
	CSRRS CSR(CSR_hpmcounter25), R0, R8
	RET

TEXT csr_write_hpmcounter25(SB), $-4
	CSRRW CSR(CSR_hpmcounter25), R8, R8
	RET

TEXT csr_set_hpmcounter25(SB), $-4
	CSRRS CSR(CSR_hpmcounter25), R8, R8
	RET

TEXT csr_clear_hpmcounter25(SB), $-4
	CSRRC CSR(CSR_hpmcounter25), R8, R8
	RET

/* hpmcounter26 */

TEXT csr_read_hpmcounter26(SB), $-4
	CSRRS CSR(CSR_hpmcounter26), R0, R8
	RET

TEXT csr_write_hpmcounter26(SB), $-4
	CSRRW CSR(CSR_hpmcounter26), R8, R8
	RET

TEXT csr_set_hpmcounter26(SB), $-4
	CSRRS CSR(CSR_hpmcounter26), R8, R8
	RET

TEXT csr_clear_hpmcounter26(SB), $-4
	CSRRC CSR(CSR_hpmcounter26), R8, R8
	RET

/* hpmcounter27 */

TEXT csr_read_hpmcounter27(SB), $-4
	CSRRS CSR(CSR_hpmcounter27), R0, R8
	RET

TEXT csr_write_hpmcounter27(SB), $-4
	CSRRW CSR(CSR_hpmcounter27), R8, R8
	RET

TEXT csr_set_hpmcounter27(SB), $-4
	CSRRS CSR(CSR_hpmcounter27), R8, R8
	RET

TEXT csr_clear_hpmcounter27(SB), $-4
	CSRRC CSR(CSR_hpmcounter27), R8, R8
	RET

/* hpmcounter28 */

TEXT csr_read_hpmcounter28(SB), $-4
	CSRRS CSR(CSR_hpmcounter28), R0, R8
	RET

TEXT csr_write_hpmcounter28(SB), $-4
	CSRRW CSR(CSR_hpmcounter28), R8, R8
	RET

TEXT csr_set_hpmcounter28(SB), $-4
	CSRRS CSR(CSR_hpmcounter28), R8, R8
	RET

TEXT csr_clear_hpmcounter28(SB), $-4
	CSRRC CSR(CSR_hpmcounter28), R8, R8
	RET

/* hpmcounter29 */

TEXT csr_read_hpmcounter29(SB), $-4
	CSRRS CSR(CSR_hpmcounter29), R0, R8
	RET

TEXT csr_write_hpmcounter29(SB), $-4
	CSRRW CSR(CSR_hpmcounter29), R8, R8
	RET

TEXT csr_set_hpmcounter29(SB), $-4
	CSRRS CSR(CSR_hpmcounter29), R8, R8
	RET

TEXT csr_clear_hpmcounter29(SB), $-4
	CSRRC CSR(CSR_hpmcounter29), R8, R8
	RET

/* hpmcounter30 */

TEXT csr_read_hpmcounter30(SB), $-4
	CSRRS CSR(CSR_hpmcounter30), R0, R8
	RET

TEXT csr_write_hpmcounter30(SB), $-4
	CSRRW CSR(CSR_hpmcounter30), R8, R8
	RET

TEXT csr_set_hpmcounter30(SB), $-4
	CSRRS CSR(CSR_hpmcounter30), R8, R8
	RET

TEXT csr_clear_hpmcounter30(SB), $-4
	CSRRC CSR(CSR_hpmcounter30), R8, R8
	RET

/* hpmcounter31 */

TEXT csr_read_hpmcounter31(SB), $-4
	CSRRS CSR(CSR_hpmcounter31), R0, R8
	RET

TEXT csr_write_hpmcounter31(SB), $-4
	CSRRW CSR(CSR_hpmcounter31), R8, R8
	RET

TEXT csr_set_hpmcounter31(SB), $-4
	CSRRS CSR(CSR_hpmcounter31), R8, R8
	RET

TEXT csr_clear_hpmcounter31(SB), $-4
	CSRRC CSR(CSR_hpmcounter31), R8, R8
	RET

/* cycleh */

TEXT csr_read_cycleh(SB), $-4
	CSRRS CSR(CSR_cycleh), R0, R8
	RET

TEXT csr_write_cycleh(SB), $-4
	CSRRW CSR(CSR_cycleh), R8, R8
	RET

TEXT csr_set_cycleh(SB), $-4
	CSRRS CSR(CSR_cycleh), R8, R8
	RET

TEXT csr_clear_cycleh(SB), $-4
	CSRRC CSR(CSR_cycleh), R8, R8
	RET

/* timeh */

TEXT csr_read_timeh(SB), $-4
	CSRRS CSR(CSR_timeh), R0, R8
	RET

TEXT csr_write_timeh(SB), $-4
	CSRRW CSR(CSR_timeh), R8, R8
	RET

TEXT csr_set_timeh(SB), $-4
	CSRRS CSR(CSR_timeh), R8, R8
	RET

TEXT csr_clear_timeh(SB), $-4
	CSRRC CSR(CSR_timeh), R8, R8
	RET

/* instreth */

TEXT csr_read_instreth(SB), $-4
	CSRRS CSR(CSR_instreth), R0, R8
	RET

TEXT csr_write_instreth(SB), $-4
	CSRRW CSR(CSR_instreth), R8, R8
	RET

TEXT csr_set_instreth(SB), $-4
	CSRRS CSR(CSR_instreth), R8, R8
	RET

TEXT csr_clear_instreth(SB), $-4
	CSRRC CSR(CSR_instreth), R8, R8
	RET

/* hpmcounter3h */

TEXT csr_read_hpmcounter3h(SB), $-4
	CSRRS CSR(CSR_hpmcounter3h), R0, R8
	RET

TEXT csr_write_hpmcounter3h(SB), $-4
	CSRRW CSR(CSR_hpmcounter3h), R8, R8
	RET

TEXT csr_set_hpmcounter3h(SB), $-4
	CSRRS CSR(CSR_hpmcounter3h), R8, R8
	RET

TEXT csr_clear_hpmcounter3h(SB), $-4
	CSRRC CSR(CSR_hpmcounter3h), R8, R8
	RET

/* hpmcounter4h */

TEXT csr_read_hpmcounter4h(SB), $-4
	CSRRS CSR(CSR_hpmcounter4h), R0, R8
	RET

TEXT csr_write_hpmcounter4h(SB), $-4
	CSRRW CSR(CSR_hpmcounter4h), R8, R8
	RET

TEXT csr_set_hpmcounter4h(SB), $-4
	CSRRS CSR(CSR_hpmcounter4h), R8, R8
	RET

TEXT csr_clear_hpmcounter4h(SB), $-4
	CSRRC CSR(CSR_hpmcounter4h), R8, R8
	RET

/* hpmcounter5h */

TEXT csr_read_hpmcounter5h(SB), $-4
	CSRRS CSR(CSR_hpmcounter5h), R0, R8
	RET

TEXT csr_write_hpmcounter5h(SB), $-4
	CSRRW CSR(CSR_hpmcounter5h), R8, R8
	RET

TEXT csr_set_hpmcounter5h(SB), $-4
	CSRRS CSR(CSR_hpmcounter5h), R8, R8
	RET

TEXT csr_clear_hpmcounter5h(SB), $-4
	CSRRC CSR(CSR_hpmcounter5h), R8, R8
	RET

/* hpmcounter6h */

TEXT csr_read_hpmcounter6h(SB), $-4
	CSRRS CSR(CSR_hpmcounter6h), R0, R8
	RET

TEXT csr_write_hpmcounter6h(SB), $-4
	CSRRW CSR(CSR_hpmcounter6h), R8, R8
	RET

TEXT csr_set_hpmcounter6h(SB), $-4
	CSRRS CSR(CSR_hpmcounter6h), R8, R8
	RET

TEXT csr_clear_hpmcounter6h(SB), $-4
	CSRRC CSR(CSR_hpmcounter6h), R8, R8
	RET

/* hpmcounter7h */

TEXT csr_read_hpmcounter7h(SB), $-4
	CSRRS CSR(CSR_hpmcounter7h), R0, R8
	RET

TEXT csr_write_hpmcounter7h(SB), $-4
	CSRRW CSR(CSR_hpmcounter7h), R8, R8
	RET

TEXT csr_set_hpmcounter7h(SB), $-4
	CSRRS CSR(CSR_hpmcounter7h), R8, R8
	RET

TEXT csr_clear_hpmcounter7h(SB), $-4
	CSRRC CSR(CSR_hpmcounter7h), R8, R8
	RET

/* hpmcounter8h */

TEXT csr_read_hpmcounter8h(SB), $-4
	CSRRS CSR(CSR_hpmcounter8h), R0, R8
	RET

TEXT csr_write_hpmcounter8h(SB), $-4
	CSRRW CSR(CSR_hpmcounter8h), R8, R8
	RET

TEXT csr_set_hpmcounter8h(SB), $-4
	CSRRS CSR(CSR_hpmcounter8h), R8, R8
	RET

TEXT csr_clear_hpmcounter8h(SB), $-4
	CSRRC CSR(CSR_hpmcounter8h), R8, R8
	RET

/* hpmcounter9h */

TEXT csr_read_hpmcounter9h(SB), $-4
	CSRRS CSR(CSR_hpmcounter9h), R0, R8
	RET

TEXT csr_write_hpmcounter9h(SB), $-4
	CSRRW CSR(CSR_hpmcounter9h), R8, R8
	RET

TEXT csr_set_hpmcounter9h(SB), $-4
	CSRRS CSR(CSR_hpmcounter9h), R8, R8
	RET

TEXT csr_clear_hpmcounter9h(SB), $-4
	CSRRC CSR(CSR_hpmcounter9h), R8, R8
	RET

/* hpmcounter10h */

TEXT csr_read_hpmcounter10h(SB), $-4
	CSRRS CSR(CSR_hpmcounter10h), R0, R8
	RET

TEXT csr_write_hpmcounter10h(SB), $-4
	CSRRW CSR(CSR_hpmcounter10h), R8, R8
	RET

TEXT csr_set_hpmcounter10h(SB), $-4
	CSRRS CSR(CSR_hpmcounter10h), R8, R8
	RET

TEXT csr_clear_hpmcounter10h(SB), $-4
	CSRRC CSR(CSR_hpmcounter10h), R8, R8
	RET

/* hpmcounter11h */

TEXT csr_read_hpmcounter11h(SB), $-4
	CSRRS CSR(CSR_hpmcounter11h), R0, R8
	RET

TEXT csr_write_hpmcounter11h(SB), $-4
	CSRRW CSR(CSR_hpmcounter11h), R8, R8
	RET

TEXT csr_set_hpmcounter11h(SB), $-4
	CSRRS CSR(CSR_hpmcounter11h), R8, R8
	RET

TEXT csr_clear_hpmcounter11h(SB), $-4
	CSRRC CSR(CSR_hpmcounter11h), R8, R8
	RET

/* hpmcounter12h */

TEXT csr_read_hpmcounter12h(SB), $-4
	CSRRS CSR(CSR_hpmcounter12h), R0, R8
	RET

TEXT csr_write_hpmcounter12h(SB), $-4
	CSRRW CSR(CSR_hpmcounter12h), R8, R8
	RET

TEXT csr_set_hpmcounter12h(SB), $-4
	CSRRS CSR(CSR_hpmcounter12h), R8, R8
	RET

TEXT csr_clear_hpmcounter12h(SB), $-4
	CSRRC CSR(CSR_hpmcounter12h), R8, R8
	RET

/* hpmcounter13h */

TEXT csr_read_hpmcounter13h(SB), $-4
	CSRRS CSR(CSR_hpmcounter13h), R0, R8
	RET

TEXT csr_write_hpmcounter13h(SB), $-4
	CSRRW CSR(CSR_hpmcounter13h), R8, R8
	RET

TEXT csr_set_hpmcounter13h(SB), $-4
	CSRRS CSR(CSR_hpmcounter13h), R8, R8
	RET

TEXT csr_clear_hpmcounter13h(SB), $-4
	CSRRC CSR(CSR_hpmcounter13h), R8, R8
	RET

/* hpmcounter14h */

TEXT csr_read_hpmcounter14h(SB), $-4
	CSRRS CSR(CSR_hpmcounter14h), R0, R8
	RET

TEXT csr_write_hpmcounter14h(SB), $-4
	CSRRW CSR(CSR_hpmcounter14h), R8, R8
	RET

TEXT csr_set_hpmcounter14h(SB), $-4
	CSRRS CSR(CSR_hpmcounter14h), R8, R8
	RET

TEXT csr_clear_hpmcounter14h(SB), $-4
	CSRRC CSR(CSR_hpmcounter14h), R8, R8
	RET

/* hpmcounter15h */

TEXT csr_read_hpmcounter15h(SB), $-4
	CSRRS CSR(CSR_hpmcounter15h), R0, R8
	RET

TEXT csr_write_hpmcounter15h(SB), $-4
	CSRRW CSR(CSR_hpmcounter15h), R8, R8
	RET

TEXT csr_set_hpmcounter15h(SB), $-4
	CSRRS CSR(CSR_hpmcounter15h), R8, R8
	RET

TEXT csr_clear_hpmcounter15h(SB), $-4
	CSRRC CSR(CSR_hpmcounter15h), R8, R8
	RET

/* hpmcounter16h */

TEXT csr_read_hpmcounter16h(SB), $-4
	CSRRS CSR(CSR_hpmcounter16h), R0, R8
	RET

TEXT csr_write_hpmcounter16h(SB), $-4
	CSRRW CSR(CSR_hpmcounter16h), R8, R8
	RET

TEXT csr_set_hpmcounter16h(SB), $-4
	CSRRS CSR(CSR_hpmcounter16h), R8, R8
	RET

TEXT csr_clear_hpmcounter16h(SB), $-4
	CSRRC CSR(CSR_hpmcounter16h), R8, R8
	RET

/* hpmcounter17h */

TEXT csr_read_hpmcounter17h(SB), $-4
	CSRRS CSR(CSR_hpmcounter17h), R0, R8
	RET

TEXT csr_write_hpmcounter17h(SB), $-4
	CSRRW CSR(CSR_hpmcounter17h), R8, R8
	RET

TEXT csr_set_hpmcounter17h(SB), $-4
	CSRRS CSR(CSR_hpmcounter17h), R8, R8
	RET

TEXT csr_clear_hpmcounter17h(SB), $-4
	CSRRC CSR(CSR_hpmcounter17h), R8, R8
	RET

/* hpmcounter18h */

TEXT csr_read_hpmcounter18h(SB), $-4
	CSRRS CSR(CSR_hpmcounter18h), R0, R8
	RET

TEXT csr_write_hpmcounter18h(SB), $-4
	CSRRW CSR(CSR_hpmcounter18h), R8, R8
	RET

TEXT csr_set_hpmcounter18h(SB), $-4
	CSRRS CSR(CSR_hpmcounter18h), R8, R8
	RET

TEXT csr_clear_hpmcounter18h(SB), $-4
	CSRRC CSR(CSR_hpmcounter18h), R8, R8
	RET

/* hpmcounter19h */

TEXT csr_read_hpmcounter19h(SB), $-4
	CSRRS CSR(CSR_hpmcounter19h), R0, R8
	RET

TEXT csr_write_hpmcounter19h(SB), $-4
	CSRRW CSR(CSR_hpmcounter19h), R8, R8
	RET

TEXT csr_set_hpmcounter19h(SB), $-4
	CSRRS CSR(CSR_hpmcounter19h), R8, R8
	RET

TEXT csr_clear_hpmcounter19h(SB), $-4
	CSRRC CSR(CSR_hpmcounter19h), R8, R8
	RET

/* hpmcounter20h */

TEXT csr_read_hpmcounter20h(SB), $-4
	CSRRS CSR(CSR_hpmcounter20h), R0, R8
	RET

TEXT csr_write_hpmcounter20h(SB), $-4
	CSRRW CSR(CSR_hpmcounter20h), R8, R8
	RET

TEXT csr_set_hpmcounter20h(SB), $-4
	CSRRS CSR(CSR_hpmcounter20h), R8, R8
	RET

TEXT csr_clear_hpmcounter20h(SB), $-4
	CSRRC CSR(CSR_hpmcounter20h), R8, R8
	RET

/* hpmcounter21h */

TEXT csr_read_hpmcounter21h(SB), $-4
	CSRRS CSR(CSR_hpmcounter21h), R0, R8
	RET

TEXT csr_write_hpmcounter21h(SB), $-4
	CSRRW CSR(CSR_hpmcounter21h), R8, R8
	RET

TEXT csr_set_hpmcounter21h(SB), $-4
	CSRRS CSR(CSR_hpmcounter21h), R8, R8
	RET

TEXT csr_clear_hpmcounter21h(SB), $-4
	CSRRC CSR(CSR_hpmcounter21h), R8, R8
	RET

/* hpmcounter22h */

TEXT csr_read_hpmcounter22h(SB), $-4
	CSRRS CSR(CSR_hpmcounter22h), R0, R8
	RET

TEXT csr_write_hpmcounter22h(SB), $-4
	CSRRW CSR(CSR_hpmcounter22h), R8, R8
	RET

TEXT csr_set_hpmcounter22h(SB), $-4
	CSRRS CSR(CSR_hpmcounter22h), R8, R8
	RET

TEXT csr_clear_hpmcounter22h(SB), $-4
	CSRRC CSR(CSR_hpmcounter22h), R8, R8
	RET

/* hpmcounter23h */

TEXT csr_read_hpmcounter23h(SB), $-4
	CSRRS CSR(CSR_hpmcounter23h), R0, R8
	RET

TEXT csr_write_hpmcounter23h(SB), $-4
	CSRRW CSR(CSR_hpmcounter23h), R8, R8
	RET

TEXT csr_set_hpmcounter23h(SB), $-4
	CSRRS CSR(CSR_hpmcounter23h), R8, R8
	RET

TEXT csr_clear_hpmcounter23h(SB), $-4
	CSRRC CSR(CSR_hpmcounter23h), R8, R8
	RET

/* hpmcounter24h */

TEXT csr_read_hpmcounter24h(SB), $-4
	CSRRS CSR(CSR_hpmcounter24h), R0, R8
	RET

TEXT csr_write_hpmcounter24h(SB), $-4
	CSRRW CSR(CSR_hpmcounter24h), R8, R8
	RET

TEXT csr_set_hpmcounter24h(SB), $-4
	CSRRS CSR(CSR_hpmcounter24h), R8, R8
	RET

TEXT csr_clear_hpmcounter24h(SB), $-4
	CSRRC CSR(CSR_hpmcounter24h), R8, R8
	RET

/* hpmcounter25h */

TEXT csr_read_hpmcounter25h(SB), $-4
	CSRRS CSR(CSR_hpmcounter25h), R0, R8
	RET

TEXT csr_write_hpmcounter25h(SB), $-4
	CSRRW CSR(CSR_hpmcounter25h), R8, R8
	RET

TEXT csr_set_hpmcounter25h(SB), $-4
	CSRRS CSR(CSR_hpmcounter25h), R8, R8
	RET

TEXT csr_clear_hpmcounter25h(SB), $-4
	CSRRC CSR(CSR_hpmcounter25h), R8, R8
	RET

/* hpmcounter26h */

TEXT csr_read_hpmcounter26h(SB), $-4
	CSRRS CSR(CSR_hpmcounter26h), R0, R8
	RET

TEXT csr_write_hpmcounter26h(SB), $-4
	CSRRW CSR(CSR_hpmcounter26h), R8, R8
	RET

TEXT csr_set_hpmcounter26h(SB), $-4
	CSRRS CSR(CSR_hpmcounter26h), R8, R8
	RET

TEXT csr_clear_hpmcounter26h(SB), $-4
	CSRRC CSR(CSR_hpmcounter26h), R8, R8
	RET

/* hpmcounter27h */

TEXT csr_read_hpmcounter27h(SB), $-4
	CSRRS CSR(CSR_hpmcounter27h), R0, R8
	RET

TEXT csr_write_hpmcounter27h(SB), $-4
	CSRRW CSR(CSR_hpmcounter27h), R8, R8
	RET

TEXT csr_set_hpmcounter27h(SB), $-4
	CSRRS CSR(CSR_hpmcounter27h), R8, R8
	RET

TEXT csr_clear_hpmcounter27h(SB), $-4
	CSRRC CSR(CSR_hpmcounter27h), R8, R8
	RET

/* hpmcounter28h */

TEXT csr_read_hpmcounter28h(SB), $-4
	CSRRS CSR(CSR_hpmcounter28h), R0, R8
	RET

TEXT csr_write_hpmcounter28h(SB), $-4
	CSRRW CSR(CSR_hpmcounter28h), R8, R8
	RET

TEXT csr_set_hpmcounter28h(SB), $-4
	CSRRS CSR(CSR_hpmcounter28h), R8, R8
	RET

TEXT csr_clear_hpmcounter28h(SB), $-4
	CSRRC CSR(CSR_hpmcounter28h), R8, R8
	RET

/* hpmcounter29h */

TEXT csr_read_hpmcounter29h(SB), $-4
	CSRRS CSR(CSR_hpmcounter29h), R0, R8
	RET

TEXT csr_write_hpmcounter29h(SB), $-4
	CSRRW CSR(CSR_hpmcounter29h), R8, R8
	RET

TEXT csr_set_hpmcounter29h(SB), $-4
	CSRRS CSR(CSR_hpmcounter29h), R8, R8
	RET

TEXT csr_clear_hpmcounter29h(SB), $-4
	CSRRC CSR(CSR_hpmcounter29h), R8, R8
	RET

/* hpmcounter30h */

TEXT csr_read_hpmcounter30h(SB), $-4
	CSRRS CSR(CSR_hpmcounter30h), R0, R8
	RET

TEXT csr_write_hpmcounter30h(SB), $-4
	CSRRW CSR(CSR_hpmcounter30h), R8, R8
	RET

TEXT csr_set_hpmcounter30h(SB), $-4
	CSRRS CSR(CSR_hpmcounter30h), R8, R8
	RET

TEXT csr_clear_hpmcounter30h(SB), $-4
	CSRRC CSR(CSR_hpmcounter30h), R8, R8
	RET

/* hpmcounter31h */

TEXT csr_read_hpmcounter31h(SB), $-4
	CSRRS CSR(CSR_hpmcounter31h), R0, R8
	RET

TEXT csr_write_hpmcounter31h(SB), $-4
	CSRRW CSR(CSR_hpmcounter31h), R8, R8
	RET

TEXT csr_set_hpmcounter31h(SB), $-4
	CSRRS CSR(CSR_hpmcounter31h), R8, R8
	RET

TEXT csr_clear_hpmcounter31h(SB), $-4
	CSRRC CSR(CSR_hpmcounter31h), R8, R8
	RET

/* sstatus */

TEXT csr_read_sstatus(SB), $-4
	CSRRS CSR(CSR_sstatus), R0, R8
	RET

TEXT csr_write_sstatus(SB), $-4
	CSRRW CSR(CSR_sstatus), R8, R8
	RET

TEXT csr_set_sstatus(SB), $-4
	CSRRS CSR(CSR_sstatus), R8, R8
	RET

TEXT csr_clear_sstatus(SB), $-4
	CSRRC CSR(CSR_sstatus), R8, R8
	RET

/* sedeleg */

TEXT csr_read_sedeleg(SB), $-4
	CSRRS CSR(CSR_sedeleg), R0, R8
	RET

TEXT csr_write_sedeleg(SB), $-4
	CSRRW CSR(CSR_sedeleg), R8, R8
	RET

TEXT csr_set_sedeleg(SB), $-4
	CSRRS CSR(CSR_sedeleg), R8, R8
	RET

TEXT csr_clear_sedeleg(SB), $-4
	CSRRC CSR(CSR_sedeleg), R8, R8
	RET

/* sideleg */

TEXT csr_read_sideleg(SB), $-4
	CSRRS CSR(CSR_sideleg), R0, R8
	RET

TEXT csr_write_sideleg(SB), $-4
	CSRRW CSR(CSR_sideleg), R8, R8
	RET

TEXT csr_set_sideleg(SB), $-4
	CSRRS CSR(CSR_sideleg), R8, R8
	RET

TEXT csr_clear_sideleg(SB), $-4
	CSRRC CSR(CSR_sideleg), R8, R8
	RET

/* sie */

TEXT csr_read_sie(SB), $-4
	CSRRS CSR(CSR_sie), R0, R8
	RET

TEXT csr_write_sie(SB), $-4
	CSRRW CSR(CSR_sie), R8, R8
	RET

TEXT csr_set_sie(SB), $-4
	CSRRS CSR(CSR_sie), R8, R8
	RET

TEXT csr_clear_sie(SB), $-4
	CSRRC CSR(CSR_sie), R8, R8
	RET

/* stvec */

TEXT csr_read_stvec(SB), $-4
	CSRRS CSR(CSR_stvec), R0, R8
	RET

TEXT csr_write_stvec(SB), $-4
	CSRRW CSR(CSR_stvec), R8, R8
	RET

TEXT csr_set_stvec(SB), $-4
	CSRRS CSR(CSR_stvec), R8, R8
	RET

TEXT csr_clear_stvec(SB), $-4
	CSRRC CSR(CSR_stvec), R8, R8
	RET

/* scounteren */

TEXT csr_read_scounteren(SB), $-4
	CSRRS CSR(CSR_scounteren), R0, R8
	RET

TEXT csr_write_scounteren(SB), $-4
	CSRRW CSR(CSR_scounteren), R8, R8
	RET

TEXT csr_set_scounteren(SB), $-4
	CSRRS CSR(CSR_scounteren), R8, R8
	RET

TEXT csr_clear_scounteren(SB), $-4
	CSRRC CSR(CSR_scounteren), R8, R8
	RET

/* sscratch */

TEXT csr_read_sscratch(SB), $-4
	CSRRS CSR(CSR_sscratch), R0, R8
	RET

TEXT csr_write_sscratch(SB), $-4
	CSRRW CSR(CSR_sscratch), R8, R8
	RET

TEXT csr_set_sscratch(SB), $-4
	CSRRS CSR(CSR_sscratch), R8, R8
	RET

TEXT csr_clear_sscratch(SB), $-4
	CSRRC CSR(CSR_sscratch), R8, R8
	RET

/* sepc */

TEXT csr_read_sepc(SB), $-4
	CSRRS CSR(CSR_sepc), R0, R8
	RET

TEXT csr_write_sepc(SB), $-4
	CSRRW CSR(CSR_sepc), R8, R8
	RET

TEXT csr_set_sepc(SB), $-4
	CSRRS CSR(CSR_sepc), R8, R8
	RET

TEXT csr_clear_sepc(SB), $-4
	CSRRC CSR(CSR_sepc), R8, R8
	RET

/* scause */

TEXT csr_read_scause(SB), $-4
	CSRRS CSR(CSR_scause), R0, R8
	RET

TEXT csr_write_scause(SB), $-4
	CSRRW CSR(CSR_scause), R8, R8
	RET

TEXT csr_set_scause(SB), $-4
	CSRRS CSR(CSR_scause), R8, R8
	RET

TEXT csr_clear_scause(SB), $-4
	CSRRC CSR(CSR_scause), R8, R8
	RET

/* stval */

TEXT csr_read_stval(SB), $-4
	CSRRS CSR(CSR_stval), R0, R8
	RET

TEXT csr_write_stval(SB), $-4
	CSRRW CSR(CSR_stval), R8, R8
	RET

TEXT csr_set_stval(SB), $-4
	CSRRS CSR(CSR_stval), R8, R8
	RET

TEXT csr_clear_stval(SB), $-4
	CSRRC CSR(CSR_stval), R8, R8
	RET

/* sip */

TEXT csr_read_sip(SB), $-4
	CSRRS CSR(CSR_sip), R0, R8
	RET

TEXT csr_write_sip(SB), $-4
	CSRRW CSR(CSR_sip), R8, R8
	RET

TEXT csr_set_sip(SB), $-4
	CSRRS CSR(CSR_sip), R8, R8
	RET

TEXT csr_clear_sip(SB), $-4
	CSRRC CSR(CSR_sip), R8, R8
	RET

/* satp */

TEXT csr_read_satp(SB), $-4
	CSRRS CSR(CSR_satp), R0, R8
	RET

TEXT csr_write_satp(SB), $-4
	CSRRW CSR(CSR_satp), R8, R8
	RET

TEXT csr_set_satp(SB), $-4
	CSRRS CSR(CSR_satp), R8, R8
	RET

TEXT csr_clear_satp(SB), $-4
	CSRRC CSR(CSR_satp), R8, R8
	RET

/* mvendorid */

TEXT csr_read_mvendorid(SB), $-4
	CSRRS CSR(CSR_mvendorid), R0, R8
	RET

TEXT csr_write_mvendorid(SB), $-4
	CSRRW CSR(CSR_mvendorid), R8, R8
	RET

TEXT csr_set_mvendorid(SB), $-4
	CSRRS CSR(CSR_mvendorid), R8, R8
	RET

TEXT csr_clear_mvendorid(SB), $-4
	CSRRC CSR(CSR_mvendorid), R8, R8
	RET

/* marchid */

TEXT csr_read_marchid(SB), $-4
	CSRRS CSR(CSR_marchid), R0, R8
	RET

TEXT csr_write_marchid(SB), $-4
	CSRRW CSR(CSR_marchid), R8, R8
	RET

TEXT csr_set_marchid(SB), $-4
	CSRRS CSR(CSR_marchid), R8, R8
	RET

TEXT csr_clear_marchid(SB), $-4
	CSRRC CSR(CSR_marchid), R8, R8
	RET

/* mimpid */

TEXT csr_read_mimpid(SB), $-4
	CSRRS CSR(CSR_mimpid), R0, R8
	RET

TEXT csr_write_mimpid(SB), $-4
	CSRRW CSR(CSR_mimpid), R8, R8
	RET

TEXT csr_set_mimpid(SB), $-4
	CSRRS CSR(CSR_mimpid), R8, R8
	RET

TEXT csr_clear_mimpid(SB), $-4
	CSRRC CSR(CSR_mimpid), R8, R8
	RET

/* mhartid */

TEXT csr_read_mhartid(SB), $-4
	CSRRS CSR(CSR_mhartid), R0, R8
	RET

TEXT csr_write_mhartid(SB), $-4
	CSRRW CSR(CSR_mhartid), R8, R8
	RET

TEXT csr_set_mhartid(SB), $-4
	CSRRS CSR(CSR_mhartid), R8, R8
	RET

TEXT csr_clear_mhartid(SB), $-4
	CSRRC CSR(CSR_mhartid), R8, R8
	RET

/* mstatus */

TEXT csr_read_mstatus(SB), $-4
	CSRRS CSR(CSR_mstatus), R0, R8
	RET

TEXT csr_write_mstatus(SB), $-4
	CSRRW CSR(CSR_mstatus), R8, R8
	RET

TEXT csr_set_mstatus(SB), $-4
	CSRRS CSR(CSR_mstatus), R8, R8
	RET

TEXT csr_clear_mstatus(SB), $-4
	CSRRC CSR(CSR_mstatus), R8, R8
	RET

/* misa */

TEXT csr_read_misa(SB), $-4
	CSRRS CSR(CSR_misa), R0, R8
	RET

TEXT csr_write_misa(SB), $-4
	CSRRW CSR(CSR_misa), R8, R8
	RET

TEXT csr_set_misa(SB), $-4
	CSRRS CSR(CSR_misa), R8, R8
	RET

TEXT csr_clear_misa(SB), $-4
	CSRRC CSR(CSR_misa), R8, R8
	RET

/* medeleg */

TEXT csr_read_medeleg(SB), $-4
	CSRRS CSR(CSR_medeleg), R0, R8
	RET

TEXT csr_write_medeleg(SB), $-4
	CSRRW CSR(CSR_medeleg), R8, R8
	RET

TEXT csr_set_medeleg(SB), $-4
	CSRRS CSR(CSR_medeleg), R8, R8
	RET

TEXT csr_clear_medeleg(SB), $-4
	CSRRC CSR(CSR_medeleg), R8, R8
	RET

/* mideleg */

TEXT csr_read_mideleg(SB), $-4
	CSRRS CSR(CSR_mideleg), R0, R8
	RET

TEXT csr_write_mideleg(SB), $-4
	CSRRW CSR(CSR_mideleg), R8, R8
	RET

TEXT csr_set_mideleg(SB), $-4
	CSRRS CSR(CSR_mideleg), R8, R8
	RET

TEXT csr_clear_mideleg(SB), $-4
	CSRRC CSR(CSR_mideleg), R8, R8
	RET

/* mie */

TEXT csr_read_mie(SB), $-4
	CSRRS CSR(CSR_mie), R0, R8
	RET

TEXT csr_write_mie(SB), $-4
	CSRRW CSR(CSR_mie), R8, R8
	RET

TEXT csr_set_mie(SB), $-4
	CSRRS CSR(CSR_mie), R8, R8
	RET

TEXT csr_clear_mie(SB), $-4
	CSRRC CSR(CSR_mie), R8, R8
	RET

/* mtvec */

TEXT csr_read_mtvec(SB), $-4
	CSRRS CSR(CSR_mtvec), R0, R8
	RET

TEXT csr_write_mtvec(SB), $-4
	CSRRW CSR(CSR_mtvec), R8, R8
	RET

TEXT csr_set_mtvec(SB), $-4
	CSRRS CSR(CSR_mtvec), R8, R8
	RET

TEXT csr_clear_mtvec(SB), $-4
	CSRRC CSR(CSR_mtvec), R8, R8
	RET

/* mcounteren */

TEXT csr_read_mcounteren(SB), $-4
	CSRRS CSR(CSR_mcounteren), R0, R8
	RET

TEXT csr_write_mcounteren(SB), $-4
	CSRRW CSR(CSR_mcounteren), R8, R8
	RET

TEXT csr_set_mcounteren(SB), $-4
	CSRRS CSR(CSR_mcounteren), R8, R8
	RET

TEXT csr_clear_mcounteren(SB), $-4
	CSRRC CSR(CSR_mcounteren), R8, R8
	RET

/* mscratch */

TEXT csr_read_mscratch(SB), $-4
	CSRRS CSR(CSR_mscratch), R0, R8
	RET

TEXT csr_write_mscratch(SB), $-4
	CSRRW CSR(CSR_mscratch), R8, R8
	RET

TEXT csr_set_mscratch(SB), $-4
	CSRRS CSR(CSR_mscratch), R8, R8
	RET

TEXT csr_clear_mscratch(SB), $-4
	CSRRC CSR(CSR_mscratch), R8, R8
	RET

/* mepc */

TEXT csr_read_mepc(SB), $-4
	CSRRS CSR(CSR_mepc), R0, R8
	RET

TEXT csr_write_mepc(SB), $-4
	CSRRW CSR(CSR_mepc), R8, R8
	RET

TEXT csr_set_mepc(SB), $-4
	CSRRS CSR(CSR_mepc), R8, R8
	RET

TEXT csr_clear_mepc(SB), $-4
	CSRRC CSR(CSR_mepc), R8, R8
	RET

/* mcause */

TEXT csr_read_mcause(SB), $-4
	CSRRS CSR(CSR_mcause), R0, R8
	RET

TEXT csr_write_mcause(SB), $-4
	CSRRW CSR(CSR_mcause), R8, R8
	RET

TEXT csr_set_mcause(SB), $-4
	CSRRS CSR(CSR_mcause), R8, R8
	RET

TEXT csr_clear_mcause(SB), $-4
	CSRRC CSR(CSR_mcause), R8, R8
	RET

/* mtval */

TEXT csr_read_mtval(SB), $-4
	CSRRS CSR(CSR_mtval), R0, R8
	RET

TEXT csr_write_mtval(SB), $-4
	CSRRW CSR(CSR_mtval), R8, R8
	RET

TEXT csr_set_mtval(SB), $-4
	CSRRS CSR(CSR_mtval), R8, R8
	RET

TEXT csr_clear_mtval(SB), $-4
	CSRRC CSR(CSR_mtval), R8, R8
	RET

/* mip */

TEXT csr_read_mip(SB), $-4
	CSRRS CSR(CSR_mip), R0, R8
	RET

TEXT csr_write_mip(SB), $-4
	CSRRW CSR(CSR_mip), R8, R8
	RET

TEXT csr_set_mip(SB), $-4
	CSRRS CSR(CSR_mip), R8, R8
	RET

TEXT csr_clear_mip(SB), $-4
	CSRRC CSR(CSR_mip), R8, R8
	RET

/* pmpcfg0 */

TEXT csr_read_pmpcfg0(SB), $-4
	CSRRS CSR(CSR_pmpcfg0), R0, R8
	RET

TEXT csr_write_pmpcfg0(SB), $-4
	CSRRW CSR(CSR_pmpcfg0), R8, R8
	RET

TEXT csr_set_pmpcfg0(SB), $-4
	CSRRS CSR(CSR_pmpcfg0), R8, R8
	RET

TEXT csr_clear_pmpcfg0(SB), $-4
	CSRRC CSR(CSR_pmpcfg0), R8, R8
	RET

/* pmpcfg1 */

TEXT csr_read_pmpcfg1(SB), $-4
	CSRRS CSR(CSR_pmpcfg1), R0, R8
	RET

TEXT csr_write_pmpcfg1(SB), $-4
	CSRRW CSR(CSR_pmpcfg1), R8, R8
	RET

TEXT csr_set_pmpcfg1(SB), $-4
	CSRRS CSR(CSR_pmpcfg1), R8, R8
	RET

TEXT csr_clear_pmpcfg1(SB), $-4
	CSRRC CSR(CSR_pmpcfg1), R8, R8
	RET

/* pmpcfg2 */

TEXT csr_read_pmpcfg2(SB), $-4
	CSRRS CSR(CSR_pmpcfg2), R0, R8
	RET

TEXT csr_write_pmpcfg2(SB), $-4
	CSRRW CSR(CSR_pmpcfg2), R8, R8
	RET

TEXT csr_set_pmpcfg2(SB), $-4
	CSRRS CSR(CSR_pmpcfg2), R8, R8
	RET

TEXT csr_clear_pmpcfg2(SB), $-4
	CSRRC CSR(CSR_pmpcfg2), R8, R8
	RET

/* pmpcfg3 */

TEXT csr_read_pmpcfg3(SB), $-4
	CSRRS CSR(CSR_pmpcfg3), R0, R8
	RET

TEXT csr_write_pmpcfg3(SB), $-4
	CSRRW CSR(CSR_pmpcfg3), R8, R8
	RET

TEXT csr_set_pmpcfg3(SB), $-4
	CSRRS CSR(CSR_pmpcfg3), R8, R8
	RET

TEXT csr_clear_pmpcfg3(SB), $-4
	CSRRC CSR(CSR_pmpcfg3), R8, R8
	RET

/* pmpaddr0 */

TEXT csr_read_pmpaddr0(SB), $-4
	CSRRS CSR(CSR_pmpaddr0), R0, R8
	RET

TEXT csr_write_pmpaddr0(SB), $-4
	CSRRW CSR(CSR_pmpaddr0), R8, R8
	RET

TEXT csr_set_pmpaddr0(SB), $-4
	CSRRS CSR(CSR_pmpaddr0), R8, R8
	RET

TEXT csr_clear_pmpaddr0(SB), $-4
	CSRRC CSR(CSR_pmpaddr0), R8, R8
	RET

/* pmpaddr1 */

TEXT csr_read_pmpaddr1(SB), $-4
	CSRRS CSR(CSR_pmpaddr1), R0, R8
	RET

TEXT csr_write_pmpaddr1(SB), $-4
	CSRRW CSR(CSR_pmpaddr1), R8, R8
	RET

TEXT csr_set_pmpaddr1(SB), $-4
	CSRRS CSR(CSR_pmpaddr1), R8, R8
	RET

TEXT csr_clear_pmpaddr1(SB), $-4
	CSRRC CSR(CSR_pmpaddr1), R8, R8
	RET

/* pmpaddr2 */

TEXT csr_read_pmpaddr2(SB), $-4
	CSRRS CSR(CSR_pmpaddr2), R0, R8
	RET

TEXT csr_write_pmpaddr2(SB), $-4
	CSRRW CSR(CSR_pmpaddr2), R8, R8
	RET

TEXT csr_set_pmpaddr2(SB), $-4
	CSRRS CSR(CSR_pmpaddr2), R8, R8
	RET

TEXT csr_clear_pmpaddr2(SB), $-4
	CSRRC CSR(CSR_pmpaddr2), R8, R8
	RET

/* pmpaddr3 */

TEXT csr_read_pmpaddr3(SB), $-4
	CSRRS CSR(CSR_pmpaddr3), R0, R8
	RET

TEXT csr_write_pmpaddr3(SB), $-4
	CSRRW CSR(CSR_pmpaddr3), R8, R8
	RET

TEXT csr_set_pmpaddr3(SB), $-4
	CSRRS CSR(CSR_pmpaddr3), R8, R8
	RET

TEXT csr_clear_pmpaddr3(SB), $-4
	CSRRC CSR(CSR_pmpaddr3), R8, R8
	RET

/* pmpaddr4 */

TEXT csr_read_pmpaddr4(SB), $-4
	CSRRS CSR(CSR_pmpaddr4), R0, R8
	RET

TEXT csr_write_pmpaddr4(SB), $-4
	CSRRW CSR(CSR_pmpaddr4), R8, R8
	RET

TEXT csr_set_pmpaddr4(SB), $-4
	CSRRS CSR(CSR_pmpaddr4), R8, R8
	RET

TEXT csr_clear_pmpaddr4(SB), $-4
	CSRRC CSR(CSR_pmpaddr4), R8, R8
	RET

/* pmpaddr5 */

TEXT csr_read_pmpaddr5(SB), $-4
	CSRRS CSR(CSR_pmpaddr5), R0, R8
	RET

TEXT csr_write_pmpaddr5(SB), $-4
	CSRRW CSR(CSR_pmpaddr5), R8, R8
	RET

TEXT csr_set_pmpaddr5(SB), $-4
	CSRRS CSR(CSR_pmpaddr5), R8, R8
	RET

TEXT csr_clear_pmpaddr5(SB), $-4
	CSRRC CSR(CSR_pmpaddr5), R8, R8
	RET

/* pmpaddr6 */

TEXT csr_read_pmpaddr6(SB), $-4
	CSRRS CSR(CSR_pmpaddr6), R0, R8
	RET

TEXT csr_write_pmpaddr6(SB), $-4
	CSRRW CSR(CSR_pmpaddr6), R8, R8
	RET

TEXT csr_set_pmpaddr6(SB), $-4
	CSRRS CSR(CSR_pmpaddr6), R8, R8
	RET

TEXT csr_clear_pmpaddr6(SB), $-4
	CSRRC CSR(CSR_pmpaddr6), R8, R8
	RET

/* pmpaddr7 */

TEXT csr_read_pmpaddr7(SB), $-4
	CSRRS CSR(CSR_pmpaddr7), R0, R8
	RET

TEXT csr_write_pmpaddr7(SB), $-4
	CSRRW CSR(CSR_pmpaddr7), R8, R8
	RET

TEXT csr_set_pmpaddr7(SB), $-4
	CSRRS CSR(CSR_pmpaddr7), R8, R8
	RET

TEXT csr_clear_pmpaddr7(SB), $-4
	CSRRC CSR(CSR_pmpaddr7), R8, R8
	RET

/* pmpaddr8 */

TEXT csr_read_pmpaddr8(SB), $-4
	CSRRS CSR(CSR_pmpaddr8), R0, R8
	RET

TEXT csr_write_pmpaddr8(SB), $-4
	CSRRW CSR(CSR_pmpaddr8), R8, R8
	RET

TEXT csr_set_pmpaddr8(SB), $-4
	CSRRS CSR(CSR_pmpaddr8), R8, R8
	RET

TEXT csr_clear_pmpaddr8(SB), $-4
	CSRRC CSR(CSR_pmpaddr8), R8, R8
	RET

/* pmpaddr9 */

TEXT csr_read_pmpaddr9(SB), $-4
	CSRRS CSR(CSR_pmpaddr9), R0, R8
	RET

TEXT csr_write_pmpaddr9(SB), $-4
	CSRRW CSR(CSR_pmpaddr9), R8, R8
	RET

TEXT csr_set_pmpaddr9(SB), $-4
	CSRRS CSR(CSR_pmpaddr9), R8, R8
	RET

TEXT csr_clear_pmpaddr9(SB), $-4
	CSRRC CSR(CSR_pmpaddr9), R8, R8
	RET

/* pmpaddr10 */

TEXT csr_read_pmpaddr10(SB), $-4
	CSRRS CSR(CSR_pmpaddr10), R0, R8
	RET

TEXT csr_write_pmpaddr10(SB), $-4
	CSRRW CSR(CSR_pmpaddr10), R8, R8
	RET

TEXT csr_set_pmpaddr10(SB), $-4
	CSRRS CSR(CSR_pmpaddr10), R8, R8
	RET

TEXT csr_clear_pmpaddr10(SB), $-4
	CSRRC CSR(CSR_pmpaddr10), R8, R8
	RET

/* pmpaddr11 */

TEXT csr_read_pmpaddr11(SB), $-4
	CSRRS CSR(CSR_pmpaddr11), R0, R8
	RET

TEXT csr_write_pmpaddr11(SB), $-4
	CSRRW CSR(CSR_pmpaddr11), R8, R8
	RET

TEXT csr_set_pmpaddr11(SB), $-4
	CSRRS CSR(CSR_pmpaddr11), R8, R8
	RET

TEXT csr_clear_pmpaddr11(SB), $-4
	CSRRC CSR(CSR_pmpaddr11), R8, R8
	RET

/* pmpaddr12 */

TEXT csr_read_pmpaddr12(SB), $-4
	CSRRS CSR(CSR_pmpaddr12), R0, R8
	RET

TEXT csr_write_pmpaddr12(SB), $-4
	CSRRW CSR(CSR_pmpaddr12), R8, R8
	RET

TEXT csr_set_pmpaddr12(SB), $-4
	CSRRS CSR(CSR_pmpaddr12), R8, R8
	RET

TEXT csr_clear_pmpaddr12(SB), $-4
	CSRRC CSR(CSR_pmpaddr12), R8, R8
	RET

/* pmpaddr13 */

TEXT csr_read_pmpaddr13(SB), $-4
	CSRRS CSR(CSR_pmpaddr13), R0, R8
	RET

TEXT csr_write_pmpaddr13(SB), $-4
	CSRRW CSR(CSR_pmpaddr13), R8, R8
	RET

TEXT csr_set_pmpaddr13(SB), $-4
	CSRRS CSR(CSR_pmpaddr13), R8, R8
	RET

TEXT csr_clear_pmpaddr13(SB), $-4
	CSRRC CSR(CSR_pmpaddr13), R8, R8
	RET

/* pmpaddr14 */

TEXT csr_read_pmpaddr14(SB), $-4
	CSRRS CSR(CSR_pmpaddr14), R0, R8
	RET

TEXT csr_write_pmpaddr14(SB), $-4
	CSRRW CSR(CSR_pmpaddr14), R8, R8
	RET

TEXT csr_set_pmpaddr14(SB), $-4
	CSRRS CSR(CSR_pmpaddr14), R8, R8
	RET

TEXT csr_clear_pmpaddr14(SB), $-4
	CSRRC CSR(CSR_pmpaddr14), R8, R8
	RET

/* pmpaddr15 */

TEXT csr_read_pmpaddr15(SB), $-4
	CSRRS CSR(CSR_pmpaddr15), R0, R8
	RET

TEXT csr_write_pmpaddr15(SB), $-4
	CSRRW CSR(CSR_pmpaddr15), R8, R8
	RET

TEXT csr_set_pmpaddr15(SB), $-4
	CSRRS CSR(CSR_pmpaddr15), R8, R8
	RET

TEXT csr_clear_pmpaddr15(SB), $-4
	CSRRC CSR(CSR_pmpaddr15), R8, R8
	RET

/* mcycle */

TEXT csr_read_mcycle(SB), $-4
	CSRRS CSR(CSR_mcycle), R0, R8
	RET

TEXT csr_write_mcycle(SB), $-4
	CSRRW CSR(CSR_mcycle), R8, R8
	RET

TEXT csr_set_mcycle(SB), $-4
	CSRRS CSR(CSR_mcycle), R8, R8
	RET

TEXT csr_clear_mcycle(SB), $-4
	CSRRC CSR(CSR_mcycle), R8, R8
	RET

/* mtime */

TEXT csr_read_mtime(SB), $-4
	CSRRS CSR(CSR_mtime), R0, R8
	RET

TEXT csr_write_mtime(SB), $-4
	CSRRW CSR(CSR_mtime), R8, R8
	RET

TEXT csr_set_mtime(SB), $-4
	CSRRS CSR(CSR_mtime), R8, R8
	RET

TEXT csr_clear_mtime(SB), $-4
	CSRRC CSR(CSR_mtime), R8, R8
	RET

/* minstret */

TEXT csr_read_minstret(SB), $-4
	CSRRS CSR(CSR_minstret), R0, R8
	RET

TEXT csr_write_minstret(SB), $-4
	CSRRW CSR(CSR_minstret), R8, R8
	RET

TEXT csr_set_minstret(SB), $-4
	CSRRS CSR(CSR_minstret), R8, R8
	RET

TEXT csr_clear_minstret(SB), $-4
	CSRRC CSR(CSR_minstret), R8, R8
	RET

/* mhpmcounter3 */

TEXT csr_read_mhpmcounter3(SB), $-4
	CSRRS CSR(CSR_mhpmcounter3), R0, R8
	RET

TEXT csr_write_mhpmcounter3(SB), $-4
	CSRRW CSR(CSR_mhpmcounter3), R8, R8
	RET

TEXT csr_set_mhpmcounter3(SB), $-4
	CSRRS CSR(CSR_mhpmcounter3), R8, R8
	RET

TEXT csr_clear_mhpmcounter3(SB), $-4
	CSRRC CSR(CSR_mhpmcounter3), R8, R8
	RET

/* mhpmcounter4 */

TEXT csr_read_mhpmcounter4(SB), $-4
	CSRRS CSR(CSR_mhpmcounter4), R0, R8
	RET

TEXT csr_write_mhpmcounter4(SB), $-4
	CSRRW CSR(CSR_mhpmcounter4), R8, R8
	RET

TEXT csr_set_mhpmcounter4(SB), $-4
	CSRRS CSR(CSR_mhpmcounter4), R8, R8
	RET

TEXT csr_clear_mhpmcounter4(SB), $-4
	CSRRC CSR(CSR_mhpmcounter4), R8, R8
	RET

/* mhpmcounter5 */

TEXT csr_read_mhpmcounter5(SB), $-4
	CSRRS CSR(CSR_mhpmcounter5), R0, R8
	RET

TEXT csr_write_mhpmcounter5(SB), $-4
	CSRRW CSR(CSR_mhpmcounter5), R8, R8
	RET

TEXT csr_set_mhpmcounter5(SB), $-4
	CSRRS CSR(CSR_mhpmcounter5), R8, R8
	RET

TEXT csr_clear_mhpmcounter5(SB), $-4
	CSRRC CSR(CSR_mhpmcounter5), R8, R8
	RET

/* mhpmcounter6 */

TEXT csr_read_mhpmcounter6(SB), $-4
	CSRRS CSR(CSR_mhpmcounter6), R0, R8
	RET

TEXT csr_write_mhpmcounter6(SB), $-4
	CSRRW CSR(CSR_mhpmcounter6), R8, R8
	RET

TEXT csr_set_mhpmcounter6(SB), $-4
	CSRRS CSR(CSR_mhpmcounter6), R8, R8
	RET

TEXT csr_clear_mhpmcounter6(SB), $-4
	CSRRC CSR(CSR_mhpmcounter6), R8, R8
	RET

/* mhpmcounter7 */

TEXT csr_read_mhpmcounter7(SB), $-4
	CSRRS CSR(CSR_mhpmcounter7), R0, R8
	RET

TEXT csr_write_mhpmcounter7(SB), $-4
	CSRRW CSR(CSR_mhpmcounter7), R8, R8
	RET

TEXT csr_set_mhpmcounter7(SB), $-4
	CSRRS CSR(CSR_mhpmcounter7), R8, R8
	RET

TEXT csr_clear_mhpmcounter7(SB), $-4
	CSRRC CSR(CSR_mhpmcounter7), R8, R8
	RET

/* mhpmcounter8 */

TEXT csr_read_mhpmcounter8(SB), $-4
	CSRRS CSR(CSR_mhpmcounter8), R0, R8
	RET

TEXT csr_write_mhpmcounter8(SB), $-4
	CSRRW CSR(CSR_mhpmcounter8), R8, R8
	RET

TEXT csr_set_mhpmcounter8(SB), $-4
	CSRRS CSR(CSR_mhpmcounter8), R8, R8
	RET

TEXT csr_clear_mhpmcounter8(SB), $-4
	CSRRC CSR(CSR_mhpmcounter8), R8, R8
	RET

/* mhpmcounter9 */

TEXT csr_read_mhpmcounter9(SB), $-4
	CSRRS CSR(CSR_mhpmcounter9), R0, R8
	RET

TEXT csr_write_mhpmcounter9(SB), $-4
	CSRRW CSR(CSR_mhpmcounter9), R8, R8
	RET

TEXT csr_set_mhpmcounter9(SB), $-4
	CSRRS CSR(CSR_mhpmcounter9), R8, R8
	RET

TEXT csr_clear_mhpmcounter9(SB), $-4
	CSRRC CSR(CSR_mhpmcounter9), R8, R8
	RET

/* mhpmcounter10 */

TEXT csr_read_mhpmcounter10(SB), $-4
	CSRRS CSR(CSR_mhpmcounter10), R0, R8
	RET

TEXT csr_write_mhpmcounter10(SB), $-4
	CSRRW CSR(CSR_mhpmcounter10), R8, R8
	RET

TEXT csr_set_mhpmcounter10(SB), $-4
	CSRRS CSR(CSR_mhpmcounter10), R8, R8
	RET

TEXT csr_clear_mhpmcounter10(SB), $-4
	CSRRC CSR(CSR_mhpmcounter10), R8, R8
	RET

/* mhpmcounter11 */

TEXT csr_read_mhpmcounter11(SB), $-4
	CSRRS CSR(CSR_mhpmcounter11), R0, R8
	RET

TEXT csr_write_mhpmcounter11(SB), $-4
	CSRRW CSR(CSR_mhpmcounter11), R8, R8
	RET

TEXT csr_set_mhpmcounter11(SB), $-4
	CSRRS CSR(CSR_mhpmcounter11), R8, R8
	RET

TEXT csr_clear_mhpmcounter11(SB), $-4
	CSRRC CSR(CSR_mhpmcounter11), R8, R8
	RET

/* mhpmcounter12 */

TEXT csr_read_mhpmcounter12(SB), $-4
	CSRRS CSR(CSR_mhpmcounter12), R0, R8
	RET

TEXT csr_write_mhpmcounter12(SB), $-4
	CSRRW CSR(CSR_mhpmcounter12), R8, R8
	RET

TEXT csr_set_mhpmcounter12(SB), $-4
	CSRRS CSR(CSR_mhpmcounter12), R8, R8
	RET

TEXT csr_clear_mhpmcounter12(SB), $-4
	CSRRC CSR(CSR_mhpmcounter12), R8, R8
	RET

/* mhpmcounter13 */

TEXT csr_read_mhpmcounter13(SB), $-4
	CSRRS CSR(CSR_mhpmcounter13), R0, R8
	RET

TEXT csr_write_mhpmcounter13(SB), $-4
	CSRRW CSR(CSR_mhpmcounter13), R8, R8
	RET

TEXT csr_set_mhpmcounter13(SB), $-4
	CSRRS CSR(CSR_mhpmcounter13), R8, R8
	RET

TEXT csr_clear_mhpmcounter13(SB), $-4
	CSRRC CSR(CSR_mhpmcounter13), R8, R8
	RET

/* mhpmcounter14 */

TEXT csr_read_mhpmcounter14(SB), $-4
	CSRRS CSR(CSR_mhpmcounter14), R0, R8
	RET

TEXT csr_write_mhpmcounter14(SB), $-4
	CSRRW CSR(CSR_mhpmcounter14), R8, R8
	RET

TEXT csr_set_mhpmcounter14(SB), $-4
	CSRRS CSR(CSR_mhpmcounter14), R8, R8
	RET

TEXT csr_clear_mhpmcounter14(SB), $-4
	CSRRC CSR(CSR_mhpmcounter14), R8, R8
	RET

/* mhpmcounter15 */

TEXT csr_read_mhpmcounter15(SB), $-4
	CSRRS CSR(CSR_mhpmcounter15), R0, R8
	RET

TEXT csr_write_mhpmcounter15(SB), $-4
	CSRRW CSR(CSR_mhpmcounter15), R8, R8
	RET

TEXT csr_set_mhpmcounter15(SB), $-4
	CSRRS CSR(CSR_mhpmcounter15), R8, R8
	RET

TEXT csr_clear_mhpmcounter15(SB), $-4
	CSRRC CSR(CSR_mhpmcounter15), R8, R8
	RET

/* mhpmcounter16 */

TEXT csr_read_mhpmcounter16(SB), $-4
	CSRRS CSR(CSR_mhpmcounter16), R0, R8
	RET

TEXT csr_write_mhpmcounter16(SB), $-4
	CSRRW CSR(CSR_mhpmcounter16), R8, R8
	RET

TEXT csr_set_mhpmcounter16(SB), $-4
	CSRRS CSR(CSR_mhpmcounter16), R8, R8
	RET

TEXT csr_clear_mhpmcounter16(SB), $-4
	CSRRC CSR(CSR_mhpmcounter16), R8, R8
	RET

/* mhpmcounter17 */

TEXT csr_read_mhpmcounter17(SB), $-4
	CSRRS CSR(CSR_mhpmcounter17), R0, R8
	RET

TEXT csr_write_mhpmcounter17(SB), $-4
	CSRRW CSR(CSR_mhpmcounter17), R8, R8
	RET

TEXT csr_set_mhpmcounter17(SB), $-4
	CSRRS CSR(CSR_mhpmcounter17), R8, R8
	RET

TEXT csr_clear_mhpmcounter17(SB), $-4
	CSRRC CSR(CSR_mhpmcounter17), R8, R8
	RET

/* mhpmcounter18 */

TEXT csr_read_mhpmcounter18(SB), $-4
	CSRRS CSR(CSR_mhpmcounter18), R0, R8
	RET

TEXT csr_write_mhpmcounter18(SB), $-4
	CSRRW CSR(CSR_mhpmcounter18), R8, R8
	RET

TEXT csr_set_mhpmcounter18(SB), $-4
	CSRRS CSR(CSR_mhpmcounter18), R8, R8
	RET

TEXT csr_clear_mhpmcounter18(SB), $-4
	CSRRC CSR(CSR_mhpmcounter18), R8, R8
	RET

/* mhpmcounter19 */

TEXT csr_read_mhpmcounter19(SB), $-4
	CSRRS CSR(CSR_mhpmcounter19), R0, R8
	RET

TEXT csr_write_mhpmcounter19(SB), $-4
	CSRRW CSR(CSR_mhpmcounter19), R8, R8
	RET

TEXT csr_set_mhpmcounter19(SB), $-4
	CSRRS CSR(CSR_mhpmcounter19), R8, R8
	RET

TEXT csr_clear_mhpmcounter19(SB), $-4
	CSRRC CSR(CSR_mhpmcounter19), R8, R8
	RET

/* mhpmcounter20 */

TEXT csr_read_mhpmcounter20(SB), $-4
	CSRRS CSR(CSR_mhpmcounter20), R0, R8
	RET

TEXT csr_write_mhpmcounter20(SB), $-4
	CSRRW CSR(CSR_mhpmcounter20), R8, R8
	RET

TEXT csr_set_mhpmcounter20(SB), $-4
	CSRRS CSR(CSR_mhpmcounter20), R8, R8
	RET

TEXT csr_clear_mhpmcounter20(SB), $-4
	CSRRC CSR(CSR_mhpmcounter20), R8, R8
	RET

/* mhpmcounter21 */

TEXT csr_read_mhpmcounter21(SB), $-4
	CSRRS CSR(CSR_mhpmcounter21), R0, R8
	RET

TEXT csr_write_mhpmcounter21(SB), $-4
	CSRRW CSR(CSR_mhpmcounter21), R8, R8
	RET

TEXT csr_set_mhpmcounter21(SB), $-4
	CSRRS CSR(CSR_mhpmcounter21), R8, R8
	RET

TEXT csr_clear_mhpmcounter21(SB), $-4
	CSRRC CSR(CSR_mhpmcounter21), R8, R8
	RET

/* mhpmcounter22 */

TEXT csr_read_mhpmcounter22(SB), $-4
	CSRRS CSR(CSR_mhpmcounter22), R0, R8
	RET

TEXT csr_write_mhpmcounter22(SB), $-4
	CSRRW CSR(CSR_mhpmcounter22), R8, R8
	RET

TEXT csr_set_mhpmcounter22(SB), $-4
	CSRRS CSR(CSR_mhpmcounter22), R8, R8
	RET

TEXT csr_clear_mhpmcounter22(SB), $-4
	CSRRC CSR(CSR_mhpmcounter22), R8, R8
	RET

/* mhpmcounter23 */

TEXT csr_read_mhpmcounter23(SB), $-4
	CSRRS CSR(CSR_mhpmcounter23), R0, R8
	RET

TEXT csr_write_mhpmcounter23(SB), $-4
	CSRRW CSR(CSR_mhpmcounter23), R8, R8
	RET

TEXT csr_set_mhpmcounter23(SB), $-4
	CSRRS CSR(CSR_mhpmcounter23), R8, R8
	RET

TEXT csr_clear_mhpmcounter23(SB), $-4
	CSRRC CSR(CSR_mhpmcounter23), R8, R8
	RET

/* mhpmcounter24 */

TEXT csr_read_mhpmcounter24(SB), $-4
	CSRRS CSR(CSR_mhpmcounter24), R0, R8
	RET

TEXT csr_write_mhpmcounter24(SB), $-4
	CSRRW CSR(CSR_mhpmcounter24), R8, R8
	RET

TEXT csr_set_mhpmcounter24(SB), $-4
	CSRRS CSR(CSR_mhpmcounter24), R8, R8
	RET

TEXT csr_clear_mhpmcounter24(SB), $-4
	CSRRC CSR(CSR_mhpmcounter24), R8, R8
	RET

/* mhpmcounter25 */

TEXT csr_read_mhpmcounter25(SB), $-4
	CSRRS CSR(CSR_mhpmcounter25), R0, R8
	RET

TEXT csr_write_mhpmcounter25(SB), $-4
	CSRRW CSR(CSR_mhpmcounter25), R8, R8
	RET

TEXT csr_set_mhpmcounter25(SB), $-4
	CSRRS CSR(CSR_mhpmcounter25), R8, R8
	RET

TEXT csr_clear_mhpmcounter25(SB), $-4
	CSRRC CSR(CSR_mhpmcounter25), R8, R8
	RET

/* mhpmcounter26 */

TEXT csr_read_mhpmcounter26(SB), $-4
	CSRRS CSR(CSR_mhpmcounter26), R0, R8
	RET

TEXT csr_write_mhpmcounter26(SB), $-4
	CSRRW CSR(CSR_mhpmcounter26), R8, R8
	RET

TEXT csr_set_mhpmcounter26(SB), $-4
	CSRRS CSR(CSR_mhpmcounter26), R8, R8
	RET

TEXT csr_clear_mhpmcounter26(SB), $-4
	CSRRC CSR(CSR_mhpmcounter26), R8, R8
	RET

/* mhpmcounter27 */

TEXT csr_read_mhpmcounter27(SB), $-4
	CSRRS CSR(CSR_mhpmcounter27), R0, R8
	RET

TEXT csr_write_mhpmcounter27(SB), $-4
	CSRRW CSR(CSR_mhpmcounter27), R8, R8
	RET

TEXT csr_set_mhpmcounter27(SB), $-4
	CSRRS CSR(CSR_mhpmcounter27), R8, R8
	RET

TEXT csr_clear_mhpmcounter27(SB), $-4
	CSRRC CSR(CSR_mhpmcounter27), R8, R8
	RET

/* mhpmcounter28 */

TEXT csr_read_mhpmcounter28(SB), $-4
	CSRRS CSR(CSR_mhpmcounter28), R0, R8
	RET

TEXT csr_write_mhpmcounter28(SB), $-4
	CSRRW CSR(CSR_mhpmcounter28), R8, R8
	RET

TEXT csr_set_mhpmcounter28(SB), $-4
	CSRRS CSR(CSR_mhpmcounter28), R8, R8
	RET

TEXT csr_clear_mhpmcounter28(SB), $-4
	CSRRC CSR(CSR_mhpmcounter28), R8, R8
	RET

/* mhpmcounter29 */

TEXT csr_read_mhpmcounter29(SB), $-4
	CSRRS CSR(CSR_mhpmcounter29), R0, R8
	RET

TEXT csr_write_mhpmcounter29(SB), $-4
	CSRRW CSR(CSR_mhpmcounter29), R8, R8
	RET

TEXT csr_set_mhpmcounter29(SB), $-4
	CSRRS CSR(CSR_mhpmcounter29), R8, R8
	RET

TEXT csr_clear_mhpmcounter29(SB), $-4
	CSRRC CSR(CSR_mhpmcounter29), R8, R8
	RET

/* mhpmcounter30 */

TEXT csr_read_mhpmcounter30(SB), $-4
	CSRRS CSR(CSR_mhpmcounter30), R0, R8
	RET

TEXT csr_write_mhpmcounter30(SB), $-4
	CSRRW CSR(CSR_mhpmcounter30), R8, R8
	RET

TEXT csr_set_mhpmcounter30(SB), $-4
	CSRRS CSR(CSR_mhpmcounter30), R8, R8
	RET

TEXT csr_clear_mhpmcounter30(SB), $-4
	CSRRC CSR(CSR_mhpmcounter30), R8, R8
	RET

/* mhpmcounter31 */

TEXT csr_read_mhpmcounter31(SB), $-4
	CSRRS CSR(CSR_mhpmcounter31), R0, R8
	RET

TEXT csr_write_mhpmcounter31(SB), $-4
	CSRRW CSR(CSR_mhpmcounter31), R8, R8
	RET

TEXT csr_set_mhpmcounter31(SB), $-4
	CSRRS CSR(CSR_mhpmcounter31), R8, R8
	RET

TEXT csr_clear_mhpmcounter31(SB), $-4
	CSRRC CSR(CSR_mhpmcounter31), R8, R8
	RET

/* mcycleh */

TEXT csr_read_mcycleh(SB), $-4
	CSRRS CSR(CSR_mcycleh), R0, R8
	RET

TEXT csr_write_mcycleh(SB), $-4
	CSRRW CSR(CSR_mcycleh), R8, R8
	RET

TEXT csr_set_mcycleh(SB), $-4
	CSRRS CSR(CSR_mcycleh), R8, R8
	RET

TEXT csr_clear_mcycleh(SB), $-4
	CSRRC CSR(CSR_mcycleh), R8, R8
	RET

/* mtimeh */

TEXT csr_read_mtimeh(SB), $-4
	CSRRS CSR(CSR_mtimeh), R0, R8
	RET

TEXT csr_write_mtimeh(SB), $-4
	CSRRW CSR(CSR_mtimeh), R8, R8
	RET

TEXT csr_set_mtimeh(SB), $-4
	CSRRS CSR(CSR_mtimeh), R8, R8
	RET

TEXT csr_clear_mtimeh(SB), $-4
	CSRRC CSR(CSR_mtimeh), R8, R8
	RET

/* minstreth */

TEXT csr_read_minstreth(SB), $-4
	CSRRS CSR(CSR_minstreth), R0, R8
	RET

TEXT csr_write_minstreth(SB), $-4
	CSRRW CSR(CSR_minstreth), R8, R8
	RET

TEXT csr_set_minstreth(SB), $-4
	CSRRS CSR(CSR_minstreth), R8, R8
	RET

TEXT csr_clear_minstreth(SB), $-4
	CSRRC CSR(CSR_minstreth), R8, R8
	RET

/* mhpmcounter3h */

TEXT csr_read_mhpmcounter3h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter3h), R0, R8
	RET

TEXT csr_write_mhpmcounter3h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter3h), R8, R8
	RET

TEXT csr_set_mhpmcounter3h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter3h), R8, R8
	RET

TEXT csr_clear_mhpmcounter3h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter3h), R8, R8
	RET

/* mhpmcounter4h */

TEXT csr_read_mhpmcounter4h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter4h), R0, R8
	RET

TEXT csr_write_mhpmcounter4h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter4h), R8, R8
	RET

TEXT csr_set_mhpmcounter4h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter4h), R8, R8
	RET

TEXT csr_clear_mhpmcounter4h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter4h), R8, R8
	RET

/* mhpmcounter5h */

TEXT csr_read_mhpmcounter5h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter5h), R0, R8
	RET

TEXT csr_write_mhpmcounter5h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter5h), R8, R8
	RET

TEXT csr_set_mhpmcounter5h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter5h), R8, R8
	RET

TEXT csr_clear_mhpmcounter5h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter5h), R8, R8
	RET

/* mhpmcounter6h */

TEXT csr_read_mhpmcounter6h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter6h), R0, R8
	RET

TEXT csr_write_mhpmcounter6h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter6h), R8, R8
	RET

TEXT csr_set_mhpmcounter6h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter6h), R8, R8
	RET

TEXT csr_clear_mhpmcounter6h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter6h), R8, R8
	RET

/* mhpmcounter7h */

TEXT csr_read_mhpmcounter7h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter7h), R0, R8
	RET

TEXT csr_write_mhpmcounter7h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter7h), R8, R8
	RET

TEXT csr_set_mhpmcounter7h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter7h), R8, R8
	RET

TEXT csr_clear_mhpmcounter7h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter7h), R8, R8
	RET

/* mhpmcounter8h */

TEXT csr_read_mhpmcounter8h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter8h), R0, R8
	RET

TEXT csr_write_mhpmcounter8h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter8h), R8, R8
	RET

TEXT csr_set_mhpmcounter8h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter8h), R8, R8
	RET

TEXT csr_clear_mhpmcounter8h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter8h), R8, R8
	RET

/* mhpmcounter9h */

TEXT csr_read_mhpmcounter9h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter9h), R0, R8
	RET

TEXT csr_write_mhpmcounter9h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter9h), R8, R8
	RET

TEXT csr_set_mhpmcounter9h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter9h), R8, R8
	RET

TEXT csr_clear_mhpmcounter9h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter9h), R8, R8
	RET

/* mhpmcounter10h */

TEXT csr_read_mhpmcounter10h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter10h), R0, R8
	RET

TEXT csr_write_mhpmcounter10h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter10h), R8, R8
	RET

TEXT csr_set_mhpmcounter10h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter10h), R8, R8
	RET

TEXT csr_clear_mhpmcounter10h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter10h), R8, R8
	RET

/* mhpmcounter11h */

TEXT csr_read_mhpmcounter11h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter11h), R0, R8
	RET

TEXT csr_write_mhpmcounter11h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter11h), R8, R8
	RET

TEXT csr_set_mhpmcounter11h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter11h), R8, R8
	RET

TEXT csr_clear_mhpmcounter11h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter11h), R8, R8
	RET

/* mhpmcounter12h */

TEXT csr_read_mhpmcounter12h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter12h), R0, R8
	RET

TEXT csr_write_mhpmcounter12h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter12h), R8, R8
	RET

TEXT csr_set_mhpmcounter12h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter12h), R8, R8
	RET

TEXT csr_clear_mhpmcounter12h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter12h), R8, R8
	RET

/* mhpmcounter13h */

TEXT csr_read_mhpmcounter13h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter13h), R0, R8
	RET

TEXT csr_write_mhpmcounter13h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter13h), R8, R8
	RET

TEXT csr_set_mhpmcounter13h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter13h), R8, R8
	RET

TEXT csr_clear_mhpmcounter13h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter13h), R8, R8
	RET

/* mhpmcounter14h */

TEXT csr_read_mhpmcounter14h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter14h), R0, R8
	RET

TEXT csr_write_mhpmcounter14h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter14h), R8, R8
	RET

TEXT csr_set_mhpmcounter14h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter14h), R8, R8
	RET

TEXT csr_clear_mhpmcounter14h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter14h), R8, R8
	RET

/* mhpmcounter15h */

TEXT csr_read_mhpmcounter15h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter15h), R0, R8
	RET

TEXT csr_write_mhpmcounter15h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter15h), R8, R8
	RET

TEXT csr_set_mhpmcounter15h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter15h), R8, R8
	RET

TEXT csr_clear_mhpmcounter15h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter15h), R8, R8
	RET

/* mhpmcounter16h */

TEXT csr_read_mhpmcounter16h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter16h), R0, R8
	RET

TEXT csr_write_mhpmcounter16h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter16h), R8, R8
	RET

TEXT csr_set_mhpmcounter16h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter16h), R8, R8
	RET

TEXT csr_clear_mhpmcounter16h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter16h), R8, R8
	RET

/* mhpmcounter17h */

TEXT csr_read_mhpmcounter17h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter17h), R0, R8
	RET

TEXT csr_write_mhpmcounter17h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter17h), R8, R8
	RET

TEXT csr_set_mhpmcounter17h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter17h), R8, R8
	RET

TEXT csr_clear_mhpmcounter17h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter17h), R8, R8
	RET

/* mhpmcounter18h */

TEXT csr_read_mhpmcounter18h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter18h), R0, R8
	RET

TEXT csr_write_mhpmcounter18h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter18h), R8, R8
	RET

TEXT csr_set_mhpmcounter18h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter18h), R8, R8
	RET

TEXT csr_clear_mhpmcounter18h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter18h), R8, R8
	RET

/* mhpmcounter19h */

TEXT csr_read_mhpmcounter19h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter19h), R0, R8
	RET

TEXT csr_write_mhpmcounter19h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter19h), R8, R8
	RET

TEXT csr_set_mhpmcounter19h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter19h), R8, R8
	RET

TEXT csr_clear_mhpmcounter19h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter19h), R8, R8
	RET

/* mhpmcounter20h */

TEXT csr_read_mhpmcounter20h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter20h), R0, R8
	RET

TEXT csr_write_mhpmcounter20h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter20h), R8, R8
	RET

TEXT csr_set_mhpmcounter20h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter20h), R8, R8
	RET

TEXT csr_clear_mhpmcounter20h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter20h), R8, R8
	RET

/* mhpmcounter21h */

TEXT csr_read_mhpmcounter21h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter21h), R0, R8
	RET

TEXT csr_write_mhpmcounter21h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter21h), R8, R8
	RET

TEXT csr_set_mhpmcounter21h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter21h), R8, R8
	RET

TEXT csr_clear_mhpmcounter21h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter21h), R8, R8
	RET

/* mhpmcounter22h */

TEXT csr_read_mhpmcounter22h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter22h), R0, R8
	RET

TEXT csr_write_mhpmcounter22h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter22h), R8, R8
	RET

TEXT csr_set_mhpmcounter22h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter22h), R8, R8
	RET

TEXT csr_clear_mhpmcounter22h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter22h), R8, R8
	RET

/* mhpmcounter23h */

TEXT csr_read_mhpmcounter23h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter23h), R0, R8
	RET

TEXT csr_write_mhpmcounter23h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter23h), R8, R8
	RET

TEXT csr_set_mhpmcounter23h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter23h), R8, R8
	RET

TEXT csr_clear_mhpmcounter23h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter23h), R8, R8
	RET

/* mhpmcounter24h */

TEXT csr_read_mhpmcounter24h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter24h), R0, R8
	RET

TEXT csr_write_mhpmcounter24h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter24h), R8, R8
	RET

TEXT csr_set_mhpmcounter24h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter24h), R8, R8
	RET

TEXT csr_clear_mhpmcounter24h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter24h), R8, R8
	RET

/* mhpmcounter25h */

TEXT csr_read_mhpmcounter25h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter25h), R0, R8
	RET

TEXT csr_write_mhpmcounter25h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter25h), R8, R8
	RET

TEXT csr_set_mhpmcounter25h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter25h), R8, R8
	RET

TEXT csr_clear_mhpmcounter25h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter25h), R8, R8
	RET

/* mhpmcounter26h */

TEXT csr_read_mhpmcounter26h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter26h), R0, R8
	RET

TEXT csr_write_mhpmcounter26h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter26h), R8, R8
	RET

TEXT csr_set_mhpmcounter26h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter26h), R8, R8
	RET

TEXT csr_clear_mhpmcounter26h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter26h), R8, R8
	RET

/* mhpmcounter27h */

TEXT csr_read_mhpmcounter27h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter27h), R0, R8
	RET

TEXT csr_write_mhpmcounter27h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter27h), R8, R8
	RET

TEXT csr_set_mhpmcounter27h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter27h), R8, R8
	RET

TEXT csr_clear_mhpmcounter27h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter27h), R8, R8
	RET

/* mhpmcounter28h */

TEXT csr_read_mhpmcounter28h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter28h), R0, R8
	RET

TEXT csr_write_mhpmcounter28h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter28h), R8, R8
	RET

TEXT csr_set_mhpmcounter28h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter28h), R8, R8
	RET

TEXT csr_clear_mhpmcounter28h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter28h), R8, R8
	RET

/* mhpmcounter29h */

TEXT csr_read_mhpmcounter29h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter29h), R0, R8
	RET

TEXT csr_write_mhpmcounter29h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter29h), R8, R8
	RET

TEXT csr_set_mhpmcounter29h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter29h), R8, R8
	RET

TEXT csr_clear_mhpmcounter29h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter29h), R8, R8
	RET

/* mhpmcounter30h */

TEXT csr_read_mhpmcounter30h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter30h), R0, R8
	RET

TEXT csr_write_mhpmcounter30h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter30h), R8, R8
	RET

TEXT csr_set_mhpmcounter30h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter30h), R8, R8
	RET

TEXT csr_clear_mhpmcounter30h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter30h), R8, R8
	RET

/* mhpmcounter31h */

TEXT csr_read_mhpmcounter31h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter31h), R0, R8
	RET

TEXT csr_write_mhpmcounter31h(SB), $-4
	CSRRW CSR(CSR_mhpmcounter31h), R8, R8
	RET

TEXT csr_set_mhpmcounter31h(SB), $-4
	CSRRS CSR(CSR_mhpmcounter31h), R8, R8
	RET

TEXT csr_clear_mhpmcounter31h(SB), $-4
	CSRRC CSR(CSR_mhpmcounter31h), R8, R8
	RET

/* mcountinhibit */

TEXT csr_read_mcountinhibit(SB), $-4
	CSRRS CSR(CSR_mcountinhibit), R0, R8
	RET

TEXT csr_write_mcountinhibit(SB), $-4
	CSRRW CSR(CSR_mcountinhibit), R8, R8
	RET

TEXT csr_set_mcountinhibit(SB), $-4
	CSRRS CSR(CSR_mcountinhibit), R8, R8
	RET

TEXT csr_clear_mcountinhibit(SB), $-4
	CSRRC CSR(CSR_mcountinhibit), R8, R8
	RET

/* mhpmevent3 */

TEXT csr_read_mhpmevent3(SB), $-4
	CSRRS CSR(CSR_mhpmevent3), R0, R8
	RET

TEXT csr_write_mhpmevent3(SB), $-4
	CSRRW CSR(CSR_mhpmevent3), R8, R8
	RET

TEXT csr_set_mhpmevent3(SB), $-4
	CSRRS CSR(CSR_mhpmevent3), R8, R8
	RET

TEXT csr_clear_mhpmevent3(SB), $-4
	CSRRC CSR(CSR_mhpmevent3), R8, R8
	RET

/* mhpmevent4 */

TEXT csr_read_mhpmevent4(SB), $-4
	CSRRS CSR(CSR_mhpmevent4), R0, R8
	RET

TEXT csr_write_mhpmevent4(SB), $-4
	CSRRW CSR(CSR_mhpmevent4), R8, R8
	RET

TEXT csr_set_mhpmevent4(SB), $-4
	CSRRS CSR(CSR_mhpmevent4), R8, R8
	RET

TEXT csr_clear_mhpmevent4(SB), $-4
	CSRRC CSR(CSR_mhpmevent4), R8, R8
	RET

/* mhpmevent5 */

TEXT csr_read_mhpmevent5(SB), $-4
	CSRRS CSR(CSR_mhpmevent5), R0, R8
	RET

TEXT csr_write_mhpmevent5(SB), $-4
	CSRRW CSR(CSR_mhpmevent5), R8, R8
	RET

TEXT csr_set_mhpmevent5(SB), $-4
	CSRRS CSR(CSR_mhpmevent5), R8, R8
	RET

TEXT csr_clear_mhpmevent5(SB), $-4
	CSRRC CSR(CSR_mhpmevent5), R8, R8
	RET

/* mhpmevent6 */

TEXT csr_read_mhpmevent6(SB), $-4
	CSRRS CSR(CSR_mhpmevent6), R0, R8
	RET

TEXT csr_write_mhpmevent6(SB), $-4
	CSRRW CSR(CSR_mhpmevent6), R8, R8
	RET

TEXT csr_set_mhpmevent6(SB), $-4
	CSRRS CSR(CSR_mhpmevent6), R8, R8
	RET

TEXT csr_clear_mhpmevent6(SB), $-4
	CSRRC CSR(CSR_mhpmevent6), R8, R8
	RET

/* mhpmevent7 */

TEXT csr_read_mhpmevent7(SB), $-4
	CSRRS CSR(CSR_mhpmevent7), R0, R8
	RET

TEXT csr_write_mhpmevent7(SB), $-4
	CSRRW CSR(CSR_mhpmevent7), R8, R8
	RET

TEXT csr_set_mhpmevent7(SB), $-4
	CSRRS CSR(CSR_mhpmevent7), R8, R8
	RET

TEXT csr_clear_mhpmevent7(SB), $-4
	CSRRC CSR(CSR_mhpmevent7), R8, R8
	RET

/* mhpmevent8 */

TEXT csr_read_mhpmevent8(SB), $-4
	CSRRS CSR(CSR_mhpmevent8), R0, R8
	RET

TEXT csr_write_mhpmevent8(SB), $-4
	CSRRW CSR(CSR_mhpmevent8), R8, R8
	RET

TEXT csr_set_mhpmevent8(SB), $-4
	CSRRS CSR(CSR_mhpmevent8), R8, R8
	RET

TEXT csr_clear_mhpmevent8(SB), $-4
	CSRRC CSR(CSR_mhpmevent8), R8, R8
	RET

/* mhpmevent9 */

TEXT csr_read_mhpmevent9(SB), $-4
	CSRRS CSR(CSR_mhpmevent9), R0, R8
	RET

TEXT csr_write_mhpmevent9(SB), $-4
	CSRRW CSR(CSR_mhpmevent9), R8, R8
	RET

TEXT csr_set_mhpmevent9(SB), $-4
	CSRRS CSR(CSR_mhpmevent9), R8, R8
	RET

TEXT csr_clear_mhpmevent9(SB), $-4
	CSRRC CSR(CSR_mhpmevent9), R8, R8
	RET

/* mhpmevent10 */

TEXT csr_read_mhpmevent10(SB), $-4
	CSRRS CSR(CSR_mhpmevent10), R0, R8
	RET

TEXT csr_write_mhpmevent10(SB), $-4
	CSRRW CSR(CSR_mhpmevent10), R8, R8
	RET

TEXT csr_set_mhpmevent10(SB), $-4
	CSRRS CSR(CSR_mhpmevent10), R8, R8
	RET

TEXT csr_clear_mhpmevent10(SB), $-4
	CSRRC CSR(CSR_mhpmevent10), R8, R8
	RET

/* mhpmevent11 */

TEXT csr_read_mhpmevent11(SB), $-4
	CSRRS CSR(CSR_mhpmevent11), R0, R8
	RET

TEXT csr_write_mhpmevent11(SB), $-4
	CSRRW CSR(CSR_mhpmevent11), R8, R8
	RET

TEXT csr_set_mhpmevent11(SB), $-4
	CSRRS CSR(CSR_mhpmevent11), R8, R8
	RET

TEXT csr_clear_mhpmevent11(SB), $-4
	CSRRC CSR(CSR_mhpmevent11), R8, R8
	RET

/* mhpmevent12 */

TEXT csr_read_mhpmevent12(SB), $-4
	CSRRS CSR(CSR_mhpmevent12), R0, R8
	RET

TEXT csr_write_mhpmevent12(SB), $-4
	CSRRW CSR(CSR_mhpmevent12), R8, R8
	RET

TEXT csr_set_mhpmevent12(SB), $-4
	CSRRS CSR(CSR_mhpmevent12), R8, R8
	RET

TEXT csr_clear_mhpmevent12(SB), $-4
	CSRRC CSR(CSR_mhpmevent12), R8, R8
	RET

/* mhpmevent13 */

TEXT csr_read_mhpmevent13(SB), $-4
	CSRRS CSR(CSR_mhpmevent13), R0, R8
	RET

TEXT csr_write_mhpmevent13(SB), $-4
	CSRRW CSR(CSR_mhpmevent13), R8, R8
	RET

TEXT csr_set_mhpmevent13(SB), $-4
	CSRRS CSR(CSR_mhpmevent13), R8, R8
	RET

TEXT csr_clear_mhpmevent13(SB), $-4
	CSRRC CSR(CSR_mhpmevent13), R8, R8
	RET

/* mhpmevent14 */

TEXT csr_read_mhpmevent14(SB), $-4
	CSRRS CSR(CSR_mhpmevent14), R0, R8
	RET

TEXT csr_write_mhpmevent14(SB), $-4
	CSRRW CSR(CSR_mhpmevent14), R8, R8
	RET

TEXT csr_set_mhpmevent14(SB), $-4
	CSRRS CSR(CSR_mhpmevent14), R8, R8
	RET

TEXT csr_clear_mhpmevent14(SB), $-4
	CSRRC CSR(CSR_mhpmevent14), R8, R8
	RET

/* mhpmevent15 */

TEXT csr_read_mhpmevent15(SB), $-4
	CSRRS CSR(CSR_mhpmevent15), R0, R8
	RET

TEXT csr_write_mhpmevent15(SB), $-4
	CSRRW CSR(CSR_mhpmevent15), R8, R8
	RET

TEXT csr_set_mhpmevent15(SB), $-4
	CSRRS CSR(CSR_mhpmevent15), R8, R8
	RET

TEXT csr_clear_mhpmevent15(SB), $-4
	CSRRC CSR(CSR_mhpmevent15), R8, R8
	RET

/* mhpmevent16 */

TEXT csr_read_mhpmevent16(SB), $-4
	CSRRS CSR(CSR_mhpmevent16), R0, R8
	RET

TEXT csr_write_mhpmevent16(SB), $-4
	CSRRW CSR(CSR_mhpmevent16), R8, R8
	RET

TEXT csr_set_mhpmevent16(SB), $-4
	CSRRS CSR(CSR_mhpmevent16), R8, R8
	RET

TEXT csr_clear_mhpmevent16(SB), $-4
	CSRRC CSR(CSR_mhpmevent16), R8, R8
	RET

/* mhpmevent17 */

TEXT csr_read_mhpmevent17(SB), $-4
	CSRRS CSR(CSR_mhpmevent17), R0, R8
	RET

TEXT csr_write_mhpmevent17(SB), $-4
	CSRRW CSR(CSR_mhpmevent17), R8, R8
	RET

TEXT csr_set_mhpmevent17(SB), $-4
	CSRRS CSR(CSR_mhpmevent17), R8, R8
	RET

TEXT csr_clear_mhpmevent17(SB), $-4
	CSRRC CSR(CSR_mhpmevent17), R8, R8
	RET

/* mhpmevent18 */

TEXT csr_read_mhpmevent18(SB), $-4
	CSRRS CSR(CSR_mhpmevent18), R0, R8
	RET

TEXT csr_write_mhpmevent18(SB), $-4
	CSRRW CSR(CSR_mhpmevent18), R8, R8
	RET

TEXT csr_set_mhpmevent18(SB), $-4
	CSRRS CSR(CSR_mhpmevent18), R8, R8
	RET

TEXT csr_clear_mhpmevent18(SB), $-4
	CSRRC CSR(CSR_mhpmevent18), R8, R8
	RET

/* mhpmevent19 */

TEXT csr_read_mhpmevent19(SB), $-4
	CSRRS CSR(CSR_mhpmevent19), R0, R8
	RET

TEXT csr_write_mhpmevent19(SB), $-4
	CSRRW CSR(CSR_mhpmevent19), R8, R8
	RET

TEXT csr_set_mhpmevent19(SB), $-4
	CSRRS CSR(CSR_mhpmevent19), R8, R8
	RET

TEXT csr_clear_mhpmevent19(SB), $-4
	CSRRC CSR(CSR_mhpmevent19), R8, R8
	RET

/* mhpmevent20 */

TEXT csr_read_mhpmevent20(SB), $-4
	CSRRS CSR(CSR_mhpmevent20), R0, R8
	RET

TEXT csr_write_mhpmevent20(SB), $-4
	CSRRW CSR(CSR_mhpmevent20), R8, R8
	RET

TEXT csr_set_mhpmevent20(SB), $-4
	CSRRS CSR(CSR_mhpmevent20), R8, R8
	RET

TEXT csr_clear_mhpmevent20(SB), $-4
	CSRRC CSR(CSR_mhpmevent20), R8, R8
	RET

/* mhpmevent21 */

TEXT csr_read_mhpmevent21(SB), $-4
	CSRRS CSR(CSR_mhpmevent21), R0, R8
	RET

TEXT csr_write_mhpmevent21(SB), $-4
	CSRRW CSR(CSR_mhpmevent21), R8, R8
	RET

TEXT csr_set_mhpmevent21(SB), $-4
	CSRRS CSR(CSR_mhpmevent21), R8, R8
	RET

TEXT csr_clear_mhpmevent21(SB), $-4
	CSRRC CSR(CSR_mhpmevent21), R8, R8
	RET

/* mhpmevent22 */

TEXT csr_read_mhpmevent22(SB), $-4
	CSRRS CSR(CSR_mhpmevent22), R0, R8
	RET

TEXT csr_write_mhpmevent22(SB), $-4
	CSRRW CSR(CSR_mhpmevent22), R8, R8
	RET

TEXT csr_set_mhpmevent22(SB), $-4
	CSRRS CSR(CSR_mhpmevent22), R8, R8
	RET

TEXT csr_clear_mhpmevent22(SB), $-4
	CSRRC CSR(CSR_mhpmevent22), R8, R8
	RET

/* mhpmevent23 */

TEXT csr_read_mhpmevent23(SB), $-4
	CSRRS CSR(CSR_mhpmevent23), R0, R8
	RET

TEXT csr_write_mhpmevent23(SB), $-4
	CSRRW CSR(CSR_mhpmevent23), R8, R8
	RET

TEXT csr_set_mhpmevent23(SB), $-4
	CSRRS CSR(CSR_mhpmevent23), R8, R8
	RET

TEXT csr_clear_mhpmevent23(SB), $-4
	CSRRC CSR(CSR_mhpmevent23), R8, R8
	RET

/* mhpmevent24 */

TEXT csr_read_mhpmevent24(SB), $-4
	CSRRS CSR(CSR_mhpmevent24), R0, R8
	RET

TEXT csr_write_mhpmevent24(SB), $-4
	CSRRW CSR(CSR_mhpmevent24), R8, R8
	RET

TEXT csr_set_mhpmevent24(SB), $-4
	CSRRS CSR(CSR_mhpmevent24), R8, R8
	RET

TEXT csr_clear_mhpmevent24(SB), $-4
	CSRRC CSR(CSR_mhpmevent24), R8, R8
	RET

/* mhpmevent25 */

TEXT csr_read_mhpmevent25(SB), $-4
	CSRRS CSR(CSR_mhpmevent25), R0, R8
	RET

TEXT csr_write_mhpmevent25(SB), $-4
	CSRRW CSR(CSR_mhpmevent25), R8, R8
	RET

TEXT csr_set_mhpmevent25(SB), $-4
	CSRRS CSR(CSR_mhpmevent25), R8, R8
	RET

TEXT csr_clear_mhpmevent25(SB), $-4
	CSRRC CSR(CSR_mhpmevent25), R8, R8
	RET

/* mhpmevent26 */

TEXT csr_read_mhpmevent26(SB), $-4
	CSRRS CSR(CSR_mhpmevent26), R0, R8
	RET

TEXT csr_write_mhpmevent26(SB), $-4
	CSRRW CSR(CSR_mhpmevent26), R8, R8
	RET

TEXT csr_set_mhpmevent26(SB), $-4
	CSRRS CSR(CSR_mhpmevent26), R8, R8
	RET

TEXT csr_clear_mhpmevent26(SB), $-4
	CSRRC CSR(CSR_mhpmevent26), R8, R8
	RET

/* mhpmevent27 */

TEXT csr_read_mhpmevent27(SB), $-4
	CSRRS CSR(CSR_mhpmevent27), R0, R8
	RET

TEXT csr_write_mhpmevent27(SB), $-4
	CSRRW CSR(CSR_mhpmevent27), R8, R8
	RET

TEXT csr_set_mhpmevent27(SB), $-4
	CSRRS CSR(CSR_mhpmevent27), R8, R8
	RET

TEXT csr_clear_mhpmevent27(SB), $-4
	CSRRC CSR(CSR_mhpmevent27), R8, R8
	RET

/* mhpmevent28 */

TEXT csr_read_mhpmevent28(SB), $-4
	CSRRS CSR(CSR_mhpmevent28), R0, R8
	RET

TEXT csr_write_mhpmevent28(SB), $-4
	CSRRW CSR(CSR_mhpmevent28), R8, R8
	RET

TEXT csr_set_mhpmevent28(SB), $-4
	CSRRS CSR(CSR_mhpmevent28), R8, R8
	RET

TEXT csr_clear_mhpmevent28(SB), $-4
	CSRRC CSR(CSR_mhpmevent28), R8, R8
	RET

/* mhpmevent29 */

TEXT csr_read_mhpmevent29(SB), $-4
	CSRRS CSR(CSR_mhpmevent29), R0, R8
	RET

TEXT csr_write_mhpmevent29(SB), $-4
	CSRRW CSR(CSR_mhpmevent29), R8, R8
	RET

TEXT csr_set_mhpmevent29(SB), $-4
	CSRRS CSR(CSR_mhpmevent29), R8, R8
	RET

TEXT csr_clear_mhpmevent29(SB), $-4
	CSRRC CSR(CSR_mhpmevent29), R8, R8
	RET

/* mhpmevent30 */

TEXT csr_read_mhpmevent30(SB), $-4
	CSRRS CSR(CSR_mhpmevent30), R0, R8
	RET

TEXT csr_write_mhpmevent30(SB), $-4
	CSRRW CSR(CSR_mhpmevent30), R8, R8
	RET

TEXT csr_set_mhpmevent30(SB), $-4
	CSRRS CSR(CSR_mhpmevent30), R8, R8
	RET

TEXT csr_clear_mhpmevent30(SB), $-4
	CSRRC CSR(CSR_mhpmevent30), R8, R8
	RET

/* mhpmevent31 */

TEXT csr_read_mhpmevent31(SB), $-4
	CSRRS CSR(CSR_mhpmevent31), R0, R8
	RET

TEXT csr_write_mhpmevent31(SB), $-4
	CSRRW CSR(CSR_mhpmevent31), R8, R8
	RET

TEXT csr_set_mhpmevent31(SB), $-4
	CSRRS CSR(CSR_mhpmevent31), R8, R8
	RET

TEXT csr_clear_mhpmevent31(SB), $-4
	CSRRC CSR(CSR_mhpmevent31), R8, R8
	RET

/* tselect */

TEXT csr_read_tselect(SB), $-4
	CSRRS CSR(CSR_tselect), R0, R8
	RET

TEXT csr_write_tselect(SB), $-4
	CSRRW CSR(CSR_tselect), R8, R8
	RET

TEXT csr_set_tselect(SB), $-4
	CSRRS CSR(CSR_tselect), R8, R8
	RET

TEXT csr_clear_tselect(SB), $-4
	CSRRC CSR(CSR_tselect), R8, R8
	RET

/* tdata1 */

TEXT csr_read_tdata1(SB), $-4
	CSRRS CSR(CSR_tdata1), R0, R8
	RET

TEXT csr_write_tdata1(SB), $-4
	CSRRW CSR(CSR_tdata1), R8, R8
	RET

TEXT csr_set_tdata1(SB), $-4
	CSRRS CSR(CSR_tdata1), R8, R8
	RET

TEXT csr_clear_tdata1(SB), $-4
	CSRRC CSR(CSR_tdata1), R8, R8
	RET

/* tdata2 */

TEXT csr_read_tdata2(SB), $-4
	CSRRS CSR(CSR_tdata2), R0, R8
	RET

TEXT csr_write_tdata2(SB), $-4
	CSRRW CSR(CSR_tdata2), R8, R8
	RET

TEXT csr_set_tdata2(SB), $-4
	CSRRS CSR(CSR_tdata2), R8, R8
	RET

TEXT csr_clear_tdata2(SB), $-4
	CSRRC CSR(CSR_tdata2), R8, R8
	RET

/* tdata3 */

TEXT csr_read_tdata3(SB), $-4
	CSRRS CSR(CSR_tdata3), R0, R8
	RET

TEXT csr_write_tdata3(SB), $-4
	CSRRW CSR(CSR_tdata3), R8, R8
	RET

TEXT csr_set_tdata3(SB), $-4
	CSRRS CSR(CSR_tdata3), R8, R8
	RET

TEXT csr_clear_tdata3(SB), $-4
	CSRRC CSR(CSR_tdata3), R8, R8
	RET

/* dcsr */

TEXT csr_read_dcsr(SB), $-4
	CSRRS CSR(CSR_dcsr), R0, R8
	RET

TEXT csr_write_dcsr(SB), $-4
	CSRRW CSR(CSR_dcsr), R8, R8
	RET

TEXT csr_set_dcsr(SB), $-4
	CSRRS CSR(CSR_dcsr), R8, R8
	RET

TEXT csr_clear_dcsr(SB), $-4
	CSRRC CSR(CSR_dcsr), R8, R8
	RET

/* dpc */

TEXT csr_read_dpc(SB), $-4
	CSRRS CSR(CSR_dpc), R0, R8
	RET

TEXT csr_write_dpc(SB), $-4
	CSRRW CSR(CSR_dpc), R8, R8
	RET

TEXT csr_set_dpc(SB), $-4
	CSRRS CSR(CSR_dpc), R8, R8
	RET

TEXT csr_clear_dpc(SB), $-4
	CSRRC CSR(CSR_dpc), R8, R8
	RET

/* dscratch0 */

TEXT csr_read_dscratch0(SB), $-4
	CSRRS CSR(CSR_dscratch0), R0, R8
	RET

TEXT csr_write_dscratch0(SB), $-4
	CSRRW CSR(CSR_dscratch0), R8, R8
	RET

TEXT csr_set_dscratch0(SB), $-4
	CSRRS CSR(CSR_dscratch0), R8, R8
	RET

TEXT csr_clear_dscratch0(SB), $-4
	CSRRC CSR(CSR_dscratch0), R8, R8
	RET

/* dscratch1 */

TEXT csr_read_dscratch1(SB), $-4
	CSRRS CSR(CSR_dscratch1), R0, R8
	RET

TEXT csr_write_dscratch1(SB), $-4
	CSRRW CSR(CSR_dscratch1), R8, R8
	RET

TEXT csr_set_dscratch1(SB), $-4
	CSRRS CSR(CSR_dscratch1), R8, R8
	RET

TEXT csr_clear_dscratch1(SB), $-4
	CSRRC CSR(CSR_dscratch1), R8, R8
	RET
