/* Autogenerated by generate_csr.sh */
#include "csrregs.h"

/*
 * This file defines three functions for each CSR, where NAME is replaced by the name of the CSR:
 * - long csr_read_NAME(void)
 *     Returns the value of the CSR
 *
 * - long csr_write_NAME(long val)
 *     Writes val to the CSR and returns the previous value
 *
 * - long csr_set_NAME(long mask)
 *     Sets the bits it CSR corresponding to high bits in the mask
 *
 * - long csr_clear_NAME(long mask)
 *     Clear the bits it CSR corresponding to high bits in the mask
 */

/* ustatus */
long csr_read_ustatus(void);
long csr_write_ustatus(long);
long csr_set_ustatus(long);
long csr_clear_ustatus(long);

/* uie */
long csr_read_uie(void);
long csr_write_uie(long);
long csr_set_uie(long);
long csr_clear_uie(long);

/* utvec */
long csr_read_utvec(void);
long csr_write_utvec(long);
long csr_set_utvec(long);
long csr_clear_utvec(long);

/* uscratch */
long csr_read_uscratch(void);
long csr_write_uscratch(long);
long csr_set_uscratch(long);
long csr_clear_uscratch(long);

/* uepc */
long csr_read_uepc(void);
long csr_write_uepc(long);
long csr_set_uepc(long);
long csr_clear_uepc(long);

/* ucause */
long csr_read_ucause(void);
long csr_write_ucause(long);
long csr_set_ucause(long);
long csr_clear_ucause(long);

/* utval */
long csr_read_utval(void);
long csr_write_utval(long);
long csr_set_utval(long);
long csr_clear_utval(long);

/* uip */
long csr_read_uip(void);
long csr_write_uip(long);
long csr_set_uip(long);
long csr_clear_uip(long);

/* fflags */
long csr_read_fflags(void);
long csr_write_fflags(long);
long csr_set_fflags(long);
long csr_clear_fflags(long);

/* frm */
long csr_read_frm(void);
long csr_write_frm(long);
long csr_set_frm(long);
long csr_clear_frm(long);

/* fcsr */
long csr_read_fcsr(void);
long csr_write_fcsr(long);
long csr_set_fcsr(long);
long csr_clear_fcsr(long);

/* cycle */
long csr_read_cycle(void);
long csr_write_cycle(long);
long csr_set_cycle(long);
long csr_clear_cycle(long);

/* time */
long csr_read_time(void);
long csr_write_time(long);
long csr_set_time(long);
long csr_clear_time(long);

/* instret */
long csr_read_instret(void);
long csr_write_instret(long);
long csr_set_instret(long);
long csr_clear_instret(long);

/* hpmcounter3 */
long csr_read_hpmcounter3(void);
long csr_write_hpmcounter3(long);
long csr_set_hpmcounter3(long);
long csr_clear_hpmcounter3(long);

/* hpmcounter4 */
long csr_read_hpmcounter4(void);
long csr_write_hpmcounter4(long);
long csr_set_hpmcounter4(long);
long csr_clear_hpmcounter4(long);

/* hpmcounter5 */
long csr_read_hpmcounter5(void);
long csr_write_hpmcounter5(long);
long csr_set_hpmcounter5(long);
long csr_clear_hpmcounter5(long);

/* hpmcounter6 */
long csr_read_hpmcounter6(void);
long csr_write_hpmcounter6(long);
long csr_set_hpmcounter6(long);
long csr_clear_hpmcounter6(long);

/* hpmcounter7 */
long csr_read_hpmcounter7(void);
long csr_write_hpmcounter7(long);
long csr_set_hpmcounter7(long);
long csr_clear_hpmcounter7(long);

/* hpmcounter8 */
long csr_read_hpmcounter8(void);
long csr_write_hpmcounter8(long);
long csr_set_hpmcounter8(long);
long csr_clear_hpmcounter8(long);

/* hpmcounter9 */
long csr_read_hpmcounter9(void);
long csr_write_hpmcounter9(long);
long csr_set_hpmcounter9(long);
long csr_clear_hpmcounter9(long);

/* hpmcounter10 */
long csr_read_hpmcounter10(void);
long csr_write_hpmcounter10(long);
long csr_set_hpmcounter10(long);
long csr_clear_hpmcounter10(long);

/* hpmcounter11 */
long csr_read_hpmcounter11(void);
long csr_write_hpmcounter11(long);
long csr_set_hpmcounter11(long);
long csr_clear_hpmcounter11(long);

/* hpmcounter12 */
long csr_read_hpmcounter12(void);
long csr_write_hpmcounter12(long);
long csr_set_hpmcounter12(long);
long csr_clear_hpmcounter12(long);

/* hpmcounter13 */
long csr_read_hpmcounter13(void);
long csr_write_hpmcounter13(long);
long csr_set_hpmcounter13(long);
long csr_clear_hpmcounter13(long);

/* hpmcounter14 */
long csr_read_hpmcounter14(void);
long csr_write_hpmcounter14(long);
long csr_set_hpmcounter14(long);
long csr_clear_hpmcounter14(long);

/* hpmcounter15 */
long csr_read_hpmcounter15(void);
long csr_write_hpmcounter15(long);
long csr_set_hpmcounter15(long);
long csr_clear_hpmcounter15(long);

/* hpmcounter16 */
long csr_read_hpmcounter16(void);
long csr_write_hpmcounter16(long);
long csr_set_hpmcounter16(long);
long csr_clear_hpmcounter16(long);

/* hpmcounter17 */
long csr_read_hpmcounter17(void);
long csr_write_hpmcounter17(long);
long csr_set_hpmcounter17(long);
long csr_clear_hpmcounter17(long);

/* hpmcounter18 */
long csr_read_hpmcounter18(void);
long csr_write_hpmcounter18(long);
long csr_set_hpmcounter18(long);
long csr_clear_hpmcounter18(long);

/* hpmcounter19 */
long csr_read_hpmcounter19(void);
long csr_write_hpmcounter19(long);
long csr_set_hpmcounter19(long);
long csr_clear_hpmcounter19(long);

/* hpmcounter20 */
long csr_read_hpmcounter20(void);
long csr_write_hpmcounter20(long);
long csr_set_hpmcounter20(long);
long csr_clear_hpmcounter20(long);

/* hpmcounter21 */
long csr_read_hpmcounter21(void);
long csr_write_hpmcounter21(long);
long csr_set_hpmcounter21(long);
long csr_clear_hpmcounter21(long);

/* hpmcounter22 */
long csr_read_hpmcounter22(void);
long csr_write_hpmcounter22(long);
long csr_set_hpmcounter22(long);
long csr_clear_hpmcounter22(long);

/* hpmcounter23 */
long csr_read_hpmcounter23(void);
long csr_write_hpmcounter23(long);
long csr_set_hpmcounter23(long);
long csr_clear_hpmcounter23(long);

/* hpmcounter24 */
long csr_read_hpmcounter24(void);
long csr_write_hpmcounter24(long);
long csr_set_hpmcounter24(long);
long csr_clear_hpmcounter24(long);

/* hpmcounter25 */
long csr_read_hpmcounter25(void);
long csr_write_hpmcounter25(long);
long csr_set_hpmcounter25(long);
long csr_clear_hpmcounter25(long);

/* hpmcounter26 */
long csr_read_hpmcounter26(void);
long csr_write_hpmcounter26(long);
long csr_set_hpmcounter26(long);
long csr_clear_hpmcounter26(long);

/* hpmcounter27 */
long csr_read_hpmcounter27(void);
long csr_write_hpmcounter27(long);
long csr_set_hpmcounter27(long);
long csr_clear_hpmcounter27(long);

/* hpmcounter28 */
long csr_read_hpmcounter28(void);
long csr_write_hpmcounter28(long);
long csr_set_hpmcounter28(long);
long csr_clear_hpmcounter28(long);

/* hpmcounter29 */
long csr_read_hpmcounter29(void);
long csr_write_hpmcounter29(long);
long csr_set_hpmcounter29(long);
long csr_clear_hpmcounter29(long);

/* hpmcounter30 */
long csr_read_hpmcounter30(void);
long csr_write_hpmcounter30(long);
long csr_set_hpmcounter30(long);
long csr_clear_hpmcounter30(long);

/* hpmcounter31 */
long csr_read_hpmcounter31(void);
long csr_write_hpmcounter31(long);
long csr_set_hpmcounter31(long);
long csr_clear_hpmcounter31(long);

/* cycleh */
long csr_read_cycleh(void);
long csr_write_cycleh(long);
long csr_set_cycleh(long);
long csr_clear_cycleh(long);

/* timeh */
long csr_read_timeh(void);
long csr_write_timeh(long);
long csr_set_timeh(long);
long csr_clear_timeh(long);

/* instreth */
long csr_read_instreth(void);
long csr_write_instreth(long);
long csr_set_instreth(long);
long csr_clear_instreth(long);

/* hpmcounter3h */
long csr_read_hpmcounter3h(void);
long csr_write_hpmcounter3h(long);
long csr_set_hpmcounter3h(long);
long csr_clear_hpmcounter3h(long);

/* hpmcounter4h */
long csr_read_hpmcounter4h(void);
long csr_write_hpmcounter4h(long);
long csr_set_hpmcounter4h(long);
long csr_clear_hpmcounter4h(long);

/* hpmcounter5h */
long csr_read_hpmcounter5h(void);
long csr_write_hpmcounter5h(long);
long csr_set_hpmcounter5h(long);
long csr_clear_hpmcounter5h(long);

/* hpmcounter6h */
long csr_read_hpmcounter6h(void);
long csr_write_hpmcounter6h(long);
long csr_set_hpmcounter6h(long);
long csr_clear_hpmcounter6h(long);

/* hpmcounter7h */
long csr_read_hpmcounter7h(void);
long csr_write_hpmcounter7h(long);
long csr_set_hpmcounter7h(long);
long csr_clear_hpmcounter7h(long);

/* hpmcounter8h */
long csr_read_hpmcounter8h(void);
long csr_write_hpmcounter8h(long);
long csr_set_hpmcounter8h(long);
long csr_clear_hpmcounter8h(long);

/* hpmcounter9h */
long csr_read_hpmcounter9h(void);
long csr_write_hpmcounter9h(long);
long csr_set_hpmcounter9h(long);
long csr_clear_hpmcounter9h(long);

/* hpmcounter10h */
long csr_read_hpmcounter10h(void);
long csr_write_hpmcounter10h(long);
long csr_set_hpmcounter10h(long);
long csr_clear_hpmcounter10h(long);

/* hpmcounter11h */
long csr_read_hpmcounter11h(void);
long csr_write_hpmcounter11h(long);
long csr_set_hpmcounter11h(long);
long csr_clear_hpmcounter11h(long);

/* hpmcounter12h */
long csr_read_hpmcounter12h(void);
long csr_write_hpmcounter12h(long);
long csr_set_hpmcounter12h(long);
long csr_clear_hpmcounter12h(long);

/* hpmcounter13h */
long csr_read_hpmcounter13h(void);
long csr_write_hpmcounter13h(long);
long csr_set_hpmcounter13h(long);
long csr_clear_hpmcounter13h(long);

/* hpmcounter14h */
long csr_read_hpmcounter14h(void);
long csr_write_hpmcounter14h(long);
long csr_set_hpmcounter14h(long);
long csr_clear_hpmcounter14h(long);

/* hpmcounter15h */
long csr_read_hpmcounter15h(void);
long csr_write_hpmcounter15h(long);
long csr_set_hpmcounter15h(long);
long csr_clear_hpmcounter15h(long);

/* hpmcounter16h */
long csr_read_hpmcounter16h(void);
long csr_write_hpmcounter16h(long);
long csr_set_hpmcounter16h(long);
long csr_clear_hpmcounter16h(long);

/* hpmcounter17h */
long csr_read_hpmcounter17h(void);
long csr_write_hpmcounter17h(long);
long csr_set_hpmcounter17h(long);
long csr_clear_hpmcounter17h(long);

/* hpmcounter18h */
long csr_read_hpmcounter18h(void);
long csr_write_hpmcounter18h(long);
long csr_set_hpmcounter18h(long);
long csr_clear_hpmcounter18h(long);

/* hpmcounter19h */
long csr_read_hpmcounter19h(void);
long csr_write_hpmcounter19h(long);
long csr_set_hpmcounter19h(long);
long csr_clear_hpmcounter19h(long);

/* hpmcounter20h */
long csr_read_hpmcounter20h(void);
long csr_write_hpmcounter20h(long);
long csr_set_hpmcounter20h(long);
long csr_clear_hpmcounter20h(long);

/* hpmcounter21h */
long csr_read_hpmcounter21h(void);
long csr_write_hpmcounter21h(long);
long csr_set_hpmcounter21h(long);
long csr_clear_hpmcounter21h(long);

/* hpmcounter22h */
long csr_read_hpmcounter22h(void);
long csr_write_hpmcounter22h(long);
long csr_set_hpmcounter22h(long);
long csr_clear_hpmcounter22h(long);

/* hpmcounter23h */
long csr_read_hpmcounter23h(void);
long csr_write_hpmcounter23h(long);
long csr_set_hpmcounter23h(long);
long csr_clear_hpmcounter23h(long);

/* hpmcounter24h */
long csr_read_hpmcounter24h(void);
long csr_write_hpmcounter24h(long);
long csr_set_hpmcounter24h(long);
long csr_clear_hpmcounter24h(long);

/* hpmcounter25h */
long csr_read_hpmcounter25h(void);
long csr_write_hpmcounter25h(long);
long csr_set_hpmcounter25h(long);
long csr_clear_hpmcounter25h(long);

/* hpmcounter26h */
long csr_read_hpmcounter26h(void);
long csr_write_hpmcounter26h(long);
long csr_set_hpmcounter26h(long);
long csr_clear_hpmcounter26h(long);

/* hpmcounter27h */
long csr_read_hpmcounter27h(void);
long csr_write_hpmcounter27h(long);
long csr_set_hpmcounter27h(long);
long csr_clear_hpmcounter27h(long);

/* hpmcounter28h */
long csr_read_hpmcounter28h(void);
long csr_write_hpmcounter28h(long);
long csr_set_hpmcounter28h(long);
long csr_clear_hpmcounter28h(long);

/* hpmcounter29h */
long csr_read_hpmcounter29h(void);
long csr_write_hpmcounter29h(long);
long csr_set_hpmcounter29h(long);
long csr_clear_hpmcounter29h(long);

/* hpmcounter30h */
long csr_read_hpmcounter30h(void);
long csr_write_hpmcounter30h(long);
long csr_set_hpmcounter30h(long);
long csr_clear_hpmcounter30h(long);

/* hpmcounter31h */
long csr_read_hpmcounter31h(void);
long csr_write_hpmcounter31h(long);
long csr_set_hpmcounter31h(long);
long csr_clear_hpmcounter31h(long);

/* sstatus */
long csr_read_sstatus(void);
long csr_write_sstatus(long);
long csr_set_sstatus(long);
long csr_clear_sstatus(long);

/* sedeleg */
long csr_read_sedeleg(void);
long csr_write_sedeleg(long);
long csr_set_sedeleg(long);
long csr_clear_sedeleg(long);

/* sideleg */
long csr_read_sideleg(void);
long csr_write_sideleg(long);
long csr_set_sideleg(long);
long csr_clear_sideleg(long);

/* sie */
long csr_read_sie(void);
long csr_write_sie(long);
long csr_set_sie(long);
long csr_clear_sie(long);

/* stvec */
long csr_read_stvec(void);
long csr_write_stvec(long);
long csr_set_stvec(long);
long csr_clear_stvec(long);

/* scounteren */
long csr_read_scounteren(void);
long csr_write_scounteren(long);
long csr_set_scounteren(long);
long csr_clear_scounteren(long);

/* sscratch */
long csr_read_sscratch(void);
long csr_write_sscratch(long);
long csr_set_sscratch(long);
long csr_clear_sscratch(long);

/* sepc */
long csr_read_sepc(void);
long csr_write_sepc(long);
long csr_set_sepc(long);
long csr_clear_sepc(long);

/* scause */
long csr_read_scause(void);
long csr_write_scause(long);
long csr_set_scause(long);
long csr_clear_scause(long);

/* stval */
long csr_read_stval(void);
long csr_write_stval(long);
long csr_set_stval(long);
long csr_clear_stval(long);

/* sip */
long csr_read_sip(void);
long csr_write_sip(long);
long csr_set_sip(long);
long csr_clear_sip(long);

/* satp */
long csr_read_satp(void);
long csr_write_satp(long);
long csr_set_satp(long);
long csr_clear_satp(long);

/* mvendorid */
long csr_read_mvendorid(void);
long csr_write_mvendorid(long);
long csr_set_mvendorid(long);
long csr_clear_mvendorid(long);

/* marchid */
long csr_read_marchid(void);
long csr_write_marchid(long);
long csr_set_marchid(long);
long csr_clear_marchid(long);

/* mimpid */
long csr_read_mimpid(void);
long csr_write_mimpid(long);
long csr_set_mimpid(long);
long csr_clear_mimpid(long);

/* mhartid */
long csr_read_mhartid(void);
long csr_write_mhartid(long);
long csr_set_mhartid(long);
long csr_clear_mhartid(long);

/* mstatus */
long csr_read_mstatus(void);
long csr_write_mstatus(long);
long csr_set_mstatus(long);
long csr_clear_mstatus(long);

/* misa */
long csr_read_misa(void);
long csr_write_misa(long);
long csr_set_misa(long);
long csr_clear_misa(long);

/* medeleg */
long csr_read_medeleg(void);
long csr_write_medeleg(long);
long csr_set_medeleg(long);
long csr_clear_medeleg(long);

/* mideleg */
long csr_read_mideleg(void);
long csr_write_mideleg(long);
long csr_set_mideleg(long);
long csr_clear_mideleg(long);

/* mie */
long csr_read_mie(void);
long csr_write_mie(long);
long csr_set_mie(long);
long csr_clear_mie(long);

/* mtvec */
long csr_read_mtvec(void);
long csr_write_mtvec(long);
long csr_set_mtvec(long);
long csr_clear_mtvec(long);

/* mcounteren */
long csr_read_mcounteren(void);
long csr_write_mcounteren(long);
long csr_set_mcounteren(long);
long csr_clear_mcounteren(long);

/* mscratch */
long csr_read_mscratch(void);
long csr_write_mscratch(long);
long csr_set_mscratch(long);
long csr_clear_mscratch(long);

/* mepc */
long csr_read_mepc(void);
long csr_write_mepc(long);
long csr_set_mepc(long);
long csr_clear_mepc(long);

/* mcause */
long csr_read_mcause(void);
long csr_write_mcause(long);
long csr_set_mcause(long);
long csr_clear_mcause(long);

/* mtval */
long csr_read_mtval(void);
long csr_write_mtval(long);
long csr_set_mtval(long);
long csr_clear_mtval(long);

/* mip */
long csr_read_mip(void);
long csr_write_mip(long);
long csr_set_mip(long);
long csr_clear_mip(long);

/* pmpcfg0 */
long csr_read_pmpcfg0(void);
long csr_write_pmpcfg0(long);
long csr_set_pmpcfg0(long);
long csr_clear_pmpcfg0(long);

/* pmpcfg1 */
long csr_read_pmpcfg1(void);
long csr_write_pmpcfg1(long);
long csr_set_pmpcfg1(long);
long csr_clear_pmpcfg1(long);

/* pmpcfg2 */
long csr_read_pmpcfg2(void);
long csr_write_pmpcfg2(long);
long csr_set_pmpcfg2(long);
long csr_clear_pmpcfg2(long);

/* pmpcfg3 */
long csr_read_pmpcfg3(void);
long csr_write_pmpcfg3(long);
long csr_set_pmpcfg3(long);
long csr_clear_pmpcfg3(long);

/* pmpaddr0 */
long csr_read_pmpaddr0(void);
long csr_write_pmpaddr0(long);
long csr_set_pmpaddr0(long);
long csr_clear_pmpaddr0(long);

/* pmpaddr1 */
long csr_read_pmpaddr1(void);
long csr_write_pmpaddr1(long);
long csr_set_pmpaddr1(long);
long csr_clear_pmpaddr1(long);

/* pmpaddr2 */
long csr_read_pmpaddr2(void);
long csr_write_pmpaddr2(long);
long csr_set_pmpaddr2(long);
long csr_clear_pmpaddr2(long);

/* pmpaddr3 */
long csr_read_pmpaddr3(void);
long csr_write_pmpaddr3(long);
long csr_set_pmpaddr3(long);
long csr_clear_pmpaddr3(long);

/* pmpaddr4 */
long csr_read_pmpaddr4(void);
long csr_write_pmpaddr4(long);
long csr_set_pmpaddr4(long);
long csr_clear_pmpaddr4(long);

/* pmpaddr5 */
long csr_read_pmpaddr5(void);
long csr_write_pmpaddr5(long);
long csr_set_pmpaddr5(long);
long csr_clear_pmpaddr5(long);

/* pmpaddr6 */
long csr_read_pmpaddr6(void);
long csr_write_pmpaddr6(long);
long csr_set_pmpaddr6(long);
long csr_clear_pmpaddr6(long);

/* pmpaddr7 */
long csr_read_pmpaddr7(void);
long csr_write_pmpaddr7(long);
long csr_set_pmpaddr7(long);
long csr_clear_pmpaddr7(long);

/* pmpaddr8 */
long csr_read_pmpaddr8(void);
long csr_write_pmpaddr8(long);
long csr_set_pmpaddr8(long);
long csr_clear_pmpaddr8(long);

/* pmpaddr9 */
long csr_read_pmpaddr9(void);
long csr_write_pmpaddr9(long);
long csr_set_pmpaddr9(long);
long csr_clear_pmpaddr9(long);

/* pmpaddr10 */
long csr_read_pmpaddr10(void);
long csr_write_pmpaddr10(long);
long csr_set_pmpaddr10(long);
long csr_clear_pmpaddr10(long);

/* pmpaddr11 */
long csr_read_pmpaddr11(void);
long csr_write_pmpaddr11(long);
long csr_set_pmpaddr11(long);
long csr_clear_pmpaddr11(long);

/* pmpaddr12 */
long csr_read_pmpaddr12(void);
long csr_write_pmpaddr12(long);
long csr_set_pmpaddr12(long);
long csr_clear_pmpaddr12(long);

/* pmpaddr13 */
long csr_read_pmpaddr13(void);
long csr_write_pmpaddr13(long);
long csr_set_pmpaddr13(long);
long csr_clear_pmpaddr13(long);

/* pmpaddr14 */
long csr_read_pmpaddr14(void);
long csr_write_pmpaddr14(long);
long csr_set_pmpaddr14(long);
long csr_clear_pmpaddr14(long);

/* pmpaddr15 */
long csr_read_pmpaddr15(void);
long csr_write_pmpaddr15(long);
long csr_set_pmpaddr15(long);
long csr_clear_pmpaddr15(long);

/* mcycle */
long csr_read_mcycle(void);
long csr_write_mcycle(long);
long csr_set_mcycle(long);
long csr_clear_mcycle(long);

/* mtime */
long csr_read_mtime(void);
long csr_write_mtime(long);
long csr_set_mtime(long);
long csr_clear_mtime(long);

/* minstret */
long csr_read_minstret(void);
long csr_write_minstret(long);
long csr_set_minstret(long);
long csr_clear_minstret(long);

/* mhpmcounter3 */
long csr_read_mhpmcounter3(void);
long csr_write_mhpmcounter3(long);
long csr_set_mhpmcounter3(long);
long csr_clear_mhpmcounter3(long);

/* mhpmcounter4 */
long csr_read_mhpmcounter4(void);
long csr_write_mhpmcounter4(long);
long csr_set_mhpmcounter4(long);
long csr_clear_mhpmcounter4(long);

/* mhpmcounter5 */
long csr_read_mhpmcounter5(void);
long csr_write_mhpmcounter5(long);
long csr_set_mhpmcounter5(long);
long csr_clear_mhpmcounter5(long);

/* mhpmcounter6 */
long csr_read_mhpmcounter6(void);
long csr_write_mhpmcounter6(long);
long csr_set_mhpmcounter6(long);
long csr_clear_mhpmcounter6(long);

/* mhpmcounter7 */
long csr_read_mhpmcounter7(void);
long csr_write_mhpmcounter7(long);
long csr_set_mhpmcounter7(long);
long csr_clear_mhpmcounter7(long);

/* mhpmcounter8 */
long csr_read_mhpmcounter8(void);
long csr_write_mhpmcounter8(long);
long csr_set_mhpmcounter8(long);
long csr_clear_mhpmcounter8(long);

/* mhpmcounter9 */
long csr_read_mhpmcounter9(void);
long csr_write_mhpmcounter9(long);
long csr_set_mhpmcounter9(long);
long csr_clear_mhpmcounter9(long);

/* mhpmcounter10 */
long csr_read_mhpmcounter10(void);
long csr_write_mhpmcounter10(long);
long csr_set_mhpmcounter10(long);
long csr_clear_mhpmcounter10(long);

/* mhpmcounter11 */
long csr_read_mhpmcounter11(void);
long csr_write_mhpmcounter11(long);
long csr_set_mhpmcounter11(long);
long csr_clear_mhpmcounter11(long);

/* mhpmcounter12 */
long csr_read_mhpmcounter12(void);
long csr_write_mhpmcounter12(long);
long csr_set_mhpmcounter12(long);
long csr_clear_mhpmcounter12(long);

/* mhpmcounter13 */
long csr_read_mhpmcounter13(void);
long csr_write_mhpmcounter13(long);
long csr_set_mhpmcounter13(long);
long csr_clear_mhpmcounter13(long);

/* mhpmcounter14 */
long csr_read_mhpmcounter14(void);
long csr_write_mhpmcounter14(long);
long csr_set_mhpmcounter14(long);
long csr_clear_mhpmcounter14(long);

/* mhpmcounter15 */
long csr_read_mhpmcounter15(void);
long csr_write_mhpmcounter15(long);
long csr_set_mhpmcounter15(long);
long csr_clear_mhpmcounter15(long);

/* mhpmcounter16 */
long csr_read_mhpmcounter16(void);
long csr_write_mhpmcounter16(long);
long csr_set_mhpmcounter16(long);
long csr_clear_mhpmcounter16(long);

/* mhpmcounter17 */
long csr_read_mhpmcounter17(void);
long csr_write_mhpmcounter17(long);
long csr_set_mhpmcounter17(long);
long csr_clear_mhpmcounter17(long);

/* mhpmcounter18 */
long csr_read_mhpmcounter18(void);
long csr_write_mhpmcounter18(long);
long csr_set_mhpmcounter18(long);
long csr_clear_mhpmcounter18(long);

/* mhpmcounter19 */
long csr_read_mhpmcounter19(void);
long csr_write_mhpmcounter19(long);
long csr_set_mhpmcounter19(long);
long csr_clear_mhpmcounter19(long);

/* mhpmcounter20 */
long csr_read_mhpmcounter20(void);
long csr_write_mhpmcounter20(long);
long csr_set_mhpmcounter20(long);
long csr_clear_mhpmcounter20(long);

/* mhpmcounter21 */
long csr_read_mhpmcounter21(void);
long csr_write_mhpmcounter21(long);
long csr_set_mhpmcounter21(long);
long csr_clear_mhpmcounter21(long);

/* mhpmcounter22 */
long csr_read_mhpmcounter22(void);
long csr_write_mhpmcounter22(long);
long csr_set_mhpmcounter22(long);
long csr_clear_mhpmcounter22(long);

/* mhpmcounter23 */
long csr_read_mhpmcounter23(void);
long csr_write_mhpmcounter23(long);
long csr_set_mhpmcounter23(long);
long csr_clear_mhpmcounter23(long);

/* mhpmcounter24 */
long csr_read_mhpmcounter24(void);
long csr_write_mhpmcounter24(long);
long csr_set_mhpmcounter24(long);
long csr_clear_mhpmcounter24(long);

/* mhpmcounter25 */
long csr_read_mhpmcounter25(void);
long csr_write_mhpmcounter25(long);
long csr_set_mhpmcounter25(long);
long csr_clear_mhpmcounter25(long);

/* mhpmcounter26 */
long csr_read_mhpmcounter26(void);
long csr_write_mhpmcounter26(long);
long csr_set_mhpmcounter26(long);
long csr_clear_mhpmcounter26(long);

/* mhpmcounter27 */
long csr_read_mhpmcounter27(void);
long csr_write_mhpmcounter27(long);
long csr_set_mhpmcounter27(long);
long csr_clear_mhpmcounter27(long);

/* mhpmcounter28 */
long csr_read_mhpmcounter28(void);
long csr_write_mhpmcounter28(long);
long csr_set_mhpmcounter28(long);
long csr_clear_mhpmcounter28(long);

/* mhpmcounter29 */
long csr_read_mhpmcounter29(void);
long csr_write_mhpmcounter29(long);
long csr_set_mhpmcounter29(long);
long csr_clear_mhpmcounter29(long);

/* mhpmcounter30 */
long csr_read_mhpmcounter30(void);
long csr_write_mhpmcounter30(long);
long csr_set_mhpmcounter30(long);
long csr_clear_mhpmcounter30(long);

/* mhpmcounter31 */
long csr_read_mhpmcounter31(void);
long csr_write_mhpmcounter31(long);
long csr_set_mhpmcounter31(long);
long csr_clear_mhpmcounter31(long);

/* mcycleh */
long csr_read_mcycleh(void);
long csr_write_mcycleh(long);
long csr_set_mcycleh(long);
long csr_clear_mcycleh(long);

/* mtimeh */
long csr_read_mtimeh(void);
long csr_write_mtimeh(long);
long csr_set_mtimeh(long);
long csr_clear_mtimeh(long);

/* minstreth */
long csr_read_minstreth(void);
long csr_write_minstreth(long);
long csr_set_minstreth(long);
long csr_clear_minstreth(long);

/* mhpmcounter3h */
long csr_read_mhpmcounter3h(void);
long csr_write_mhpmcounter3h(long);
long csr_set_mhpmcounter3h(long);
long csr_clear_mhpmcounter3h(long);

/* mhpmcounter4h */
long csr_read_mhpmcounter4h(void);
long csr_write_mhpmcounter4h(long);
long csr_set_mhpmcounter4h(long);
long csr_clear_mhpmcounter4h(long);

/* mhpmcounter5h */
long csr_read_mhpmcounter5h(void);
long csr_write_mhpmcounter5h(long);
long csr_set_mhpmcounter5h(long);
long csr_clear_mhpmcounter5h(long);

/* mhpmcounter6h */
long csr_read_mhpmcounter6h(void);
long csr_write_mhpmcounter6h(long);
long csr_set_mhpmcounter6h(long);
long csr_clear_mhpmcounter6h(long);

/* mhpmcounter7h */
long csr_read_mhpmcounter7h(void);
long csr_write_mhpmcounter7h(long);
long csr_set_mhpmcounter7h(long);
long csr_clear_mhpmcounter7h(long);

/* mhpmcounter8h */
long csr_read_mhpmcounter8h(void);
long csr_write_mhpmcounter8h(long);
long csr_set_mhpmcounter8h(long);
long csr_clear_mhpmcounter8h(long);

/* mhpmcounter9h */
long csr_read_mhpmcounter9h(void);
long csr_write_mhpmcounter9h(long);
long csr_set_mhpmcounter9h(long);
long csr_clear_mhpmcounter9h(long);

/* mhpmcounter10h */
long csr_read_mhpmcounter10h(void);
long csr_write_mhpmcounter10h(long);
long csr_set_mhpmcounter10h(long);
long csr_clear_mhpmcounter10h(long);

/* mhpmcounter11h */
long csr_read_mhpmcounter11h(void);
long csr_write_mhpmcounter11h(long);
long csr_set_mhpmcounter11h(long);
long csr_clear_mhpmcounter11h(long);

/* mhpmcounter12h */
long csr_read_mhpmcounter12h(void);
long csr_write_mhpmcounter12h(long);
long csr_set_mhpmcounter12h(long);
long csr_clear_mhpmcounter12h(long);

/* mhpmcounter13h */
long csr_read_mhpmcounter13h(void);
long csr_write_mhpmcounter13h(long);
long csr_set_mhpmcounter13h(long);
long csr_clear_mhpmcounter13h(long);

/* mhpmcounter14h */
long csr_read_mhpmcounter14h(void);
long csr_write_mhpmcounter14h(long);
long csr_set_mhpmcounter14h(long);
long csr_clear_mhpmcounter14h(long);

/* mhpmcounter15h */
long csr_read_mhpmcounter15h(void);
long csr_write_mhpmcounter15h(long);
long csr_set_mhpmcounter15h(long);
long csr_clear_mhpmcounter15h(long);

/* mhpmcounter16h */
long csr_read_mhpmcounter16h(void);
long csr_write_mhpmcounter16h(long);
long csr_set_mhpmcounter16h(long);
long csr_clear_mhpmcounter16h(long);

/* mhpmcounter17h */
long csr_read_mhpmcounter17h(void);
long csr_write_mhpmcounter17h(long);
long csr_set_mhpmcounter17h(long);
long csr_clear_mhpmcounter17h(long);

/* mhpmcounter18h */
long csr_read_mhpmcounter18h(void);
long csr_write_mhpmcounter18h(long);
long csr_set_mhpmcounter18h(long);
long csr_clear_mhpmcounter18h(long);

/* mhpmcounter19h */
long csr_read_mhpmcounter19h(void);
long csr_write_mhpmcounter19h(long);
long csr_set_mhpmcounter19h(long);
long csr_clear_mhpmcounter19h(long);

/* mhpmcounter20h */
long csr_read_mhpmcounter20h(void);
long csr_write_mhpmcounter20h(long);
long csr_set_mhpmcounter20h(long);
long csr_clear_mhpmcounter20h(long);

/* mhpmcounter21h */
long csr_read_mhpmcounter21h(void);
long csr_write_mhpmcounter21h(long);
long csr_set_mhpmcounter21h(long);
long csr_clear_mhpmcounter21h(long);

/* mhpmcounter22h */
long csr_read_mhpmcounter22h(void);
long csr_write_mhpmcounter22h(long);
long csr_set_mhpmcounter22h(long);
long csr_clear_mhpmcounter22h(long);

/* mhpmcounter23h */
long csr_read_mhpmcounter23h(void);
long csr_write_mhpmcounter23h(long);
long csr_set_mhpmcounter23h(long);
long csr_clear_mhpmcounter23h(long);

/* mhpmcounter24h */
long csr_read_mhpmcounter24h(void);
long csr_write_mhpmcounter24h(long);
long csr_set_mhpmcounter24h(long);
long csr_clear_mhpmcounter24h(long);

/* mhpmcounter25h */
long csr_read_mhpmcounter25h(void);
long csr_write_mhpmcounter25h(long);
long csr_set_mhpmcounter25h(long);
long csr_clear_mhpmcounter25h(long);

/* mhpmcounter26h */
long csr_read_mhpmcounter26h(void);
long csr_write_mhpmcounter26h(long);
long csr_set_mhpmcounter26h(long);
long csr_clear_mhpmcounter26h(long);

/* mhpmcounter27h */
long csr_read_mhpmcounter27h(void);
long csr_write_mhpmcounter27h(long);
long csr_set_mhpmcounter27h(long);
long csr_clear_mhpmcounter27h(long);

/* mhpmcounter28h */
long csr_read_mhpmcounter28h(void);
long csr_write_mhpmcounter28h(long);
long csr_set_mhpmcounter28h(long);
long csr_clear_mhpmcounter28h(long);

/* mhpmcounter29h */
long csr_read_mhpmcounter29h(void);
long csr_write_mhpmcounter29h(long);
long csr_set_mhpmcounter29h(long);
long csr_clear_mhpmcounter29h(long);

/* mhpmcounter30h */
long csr_read_mhpmcounter30h(void);
long csr_write_mhpmcounter30h(long);
long csr_set_mhpmcounter30h(long);
long csr_clear_mhpmcounter30h(long);

/* mhpmcounter31h */
long csr_read_mhpmcounter31h(void);
long csr_write_mhpmcounter31h(long);
long csr_set_mhpmcounter31h(long);
long csr_clear_mhpmcounter31h(long);

/* mcountinhibit */
long csr_read_mcountinhibit(void);
long csr_write_mcountinhibit(long);
long csr_set_mcountinhibit(long);
long csr_clear_mcountinhibit(long);

/* mhpmevent3 */
long csr_read_mhpmevent3(void);
long csr_write_mhpmevent3(long);
long csr_set_mhpmevent3(long);
long csr_clear_mhpmevent3(long);

/* mhpmevent4 */
long csr_read_mhpmevent4(void);
long csr_write_mhpmevent4(long);
long csr_set_mhpmevent4(long);
long csr_clear_mhpmevent4(long);

/* mhpmevent5 */
long csr_read_mhpmevent5(void);
long csr_write_mhpmevent5(long);
long csr_set_mhpmevent5(long);
long csr_clear_mhpmevent5(long);

/* mhpmevent6 */
long csr_read_mhpmevent6(void);
long csr_write_mhpmevent6(long);
long csr_set_mhpmevent6(long);
long csr_clear_mhpmevent6(long);

/* mhpmevent7 */
long csr_read_mhpmevent7(void);
long csr_write_mhpmevent7(long);
long csr_set_mhpmevent7(long);
long csr_clear_mhpmevent7(long);

/* mhpmevent8 */
long csr_read_mhpmevent8(void);
long csr_write_mhpmevent8(long);
long csr_set_mhpmevent8(long);
long csr_clear_mhpmevent8(long);

/* mhpmevent9 */
long csr_read_mhpmevent9(void);
long csr_write_mhpmevent9(long);
long csr_set_mhpmevent9(long);
long csr_clear_mhpmevent9(long);

/* mhpmevent10 */
long csr_read_mhpmevent10(void);
long csr_write_mhpmevent10(long);
long csr_set_mhpmevent10(long);
long csr_clear_mhpmevent10(long);

/* mhpmevent11 */
long csr_read_mhpmevent11(void);
long csr_write_mhpmevent11(long);
long csr_set_mhpmevent11(long);
long csr_clear_mhpmevent11(long);

/* mhpmevent12 */
long csr_read_mhpmevent12(void);
long csr_write_mhpmevent12(long);
long csr_set_mhpmevent12(long);
long csr_clear_mhpmevent12(long);

/* mhpmevent13 */
long csr_read_mhpmevent13(void);
long csr_write_mhpmevent13(long);
long csr_set_mhpmevent13(long);
long csr_clear_mhpmevent13(long);

/* mhpmevent14 */
long csr_read_mhpmevent14(void);
long csr_write_mhpmevent14(long);
long csr_set_mhpmevent14(long);
long csr_clear_mhpmevent14(long);

/* mhpmevent15 */
long csr_read_mhpmevent15(void);
long csr_write_mhpmevent15(long);
long csr_set_mhpmevent15(long);
long csr_clear_mhpmevent15(long);

/* mhpmevent16 */
long csr_read_mhpmevent16(void);
long csr_write_mhpmevent16(long);
long csr_set_mhpmevent16(long);
long csr_clear_mhpmevent16(long);

/* mhpmevent17 */
long csr_read_mhpmevent17(void);
long csr_write_mhpmevent17(long);
long csr_set_mhpmevent17(long);
long csr_clear_mhpmevent17(long);

/* mhpmevent18 */
long csr_read_mhpmevent18(void);
long csr_write_mhpmevent18(long);
long csr_set_mhpmevent18(long);
long csr_clear_mhpmevent18(long);

/* mhpmevent19 */
long csr_read_mhpmevent19(void);
long csr_write_mhpmevent19(long);
long csr_set_mhpmevent19(long);
long csr_clear_mhpmevent19(long);

/* mhpmevent20 */
long csr_read_mhpmevent20(void);
long csr_write_mhpmevent20(long);
long csr_set_mhpmevent20(long);
long csr_clear_mhpmevent20(long);

/* mhpmevent21 */
long csr_read_mhpmevent21(void);
long csr_write_mhpmevent21(long);
long csr_set_mhpmevent21(long);
long csr_clear_mhpmevent21(long);

/* mhpmevent22 */
long csr_read_mhpmevent22(void);
long csr_write_mhpmevent22(long);
long csr_set_mhpmevent22(long);
long csr_clear_mhpmevent22(long);

/* mhpmevent23 */
long csr_read_mhpmevent23(void);
long csr_write_mhpmevent23(long);
long csr_set_mhpmevent23(long);
long csr_clear_mhpmevent23(long);

/* mhpmevent24 */
long csr_read_mhpmevent24(void);
long csr_write_mhpmevent24(long);
long csr_set_mhpmevent24(long);
long csr_clear_mhpmevent24(long);

/* mhpmevent25 */
long csr_read_mhpmevent25(void);
long csr_write_mhpmevent25(long);
long csr_set_mhpmevent25(long);
long csr_clear_mhpmevent25(long);

/* mhpmevent26 */
long csr_read_mhpmevent26(void);
long csr_write_mhpmevent26(long);
long csr_set_mhpmevent26(long);
long csr_clear_mhpmevent26(long);

/* mhpmevent27 */
long csr_read_mhpmevent27(void);
long csr_write_mhpmevent27(long);
long csr_set_mhpmevent27(long);
long csr_clear_mhpmevent27(long);

/* mhpmevent28 */
long csr_read_mhpmevent28(void);
long csr_write_mhpmevent28(long);
long csr_set_mhpmevent28(long);
long csr_clear_mhpmevent28(long);

/* mhpmevent29 */
long csr_read_mhpmevent29(void);
long csr_write_mhpmevent29(long);
long csr_set_mhpmevent29(long);
long csr_clear_mhpmevent29(long);

/* mhpmevent30 */
long csr_read_mhpmevent30(void);
long csr_write_mhpmevent30(long);
long csr_set_mhpmevent30(long);
long csr_clear_mhpmevent30(long);

/* mhpmevent31 */
long csr_read_mhpmevent31(void);
long csr_write_mhpmevent31(long);
long csr_set_mhpmevent31(long);
long csr_clear_mhpmevent31(long);

/* tselect */
long csr_read_tselect(void);
long csr_write_tselect(long);
long csr_set_tselect(long);
long csr_clear_tselect(long);

/* tdata1 */
long csr_read_tdata1(void);
long csr_write_tdata1(long);
long csr_set_tdata1(long);
long csr_clear_tdata1(long);

/* tdata2 */
long csr_read_tdata2(void);
long csr_write_tdata2(long);
long csr_set_tdata2(long);
long csr_clear_tdata2(long);

/* tdata3 */
long csr_read_tdata3(void);
long csr_write_tdata3(long);
long csr_set_tdata3(long);
long csr_clear_tdata3(long);

/* dcsr */
long csr_read_dcsr(void);
long csr_write_dcsr(long);
long csr_set_dcsr(long);
long csr_clear_dcsr(long);

/* dpc */
long csr_read_dpc(void);
long csr_write_dpc(long);
long csr_set_dpc(long);
long csr_clear_dpc(long);

/* dscratch0 */
long csr_read_dscratch0(void);
long csr_write_dscratch0(long);
long csr_set_dscratch0(long);
long csr_clear_dscratch0(long);

/* dscratch1 */
long csr_read_dscratch1(void);
long csr_write_dscratch1(long);
long csr_set_dscratch1(long);
long csr_clear_dscratch1(long);
